### ISSUE TITLE
Please consider bringing back the image rotation button

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1009]
Removing the image rotate button and replacing it with a three finger gesture as the only option was not the best change in my personal opinion. The gesture seems a bit difficult to activate, at least on my phone, with taps occasionally not registering or registering as a zoom/swipe. Another thing to consider is that the three finger gesture is already being used as a gesture to take a screenshot on several manufacturers' stock ROM (Motorola, Xiaomi, Huawei and Realme, possibly others).

I would like the toolbar rotate button brought back, at least as an optional feature. You could have a setting for image rotation with three options:
- menu option
- toolbar button
- three finger gesture

**Comment by Adamantcheese** [comment]
The reason for the original menu option, the toolbar menu button, and now the gesture is that _way_ back when I even added the original rotation option I wanted to have a two-finger free rotation, however because of https://github.com/davemorrissey/subsampling-scale-image-view/issues/149, it's not really possible. This is probably the closest I'll be able to get. Works well now and doesn't interfere with the pan/zoom functions.

**Comment by Astridchan** [comment]
Yeah, the new gesture works a lot better. I think there should be a pop-up hint that shows up on first install that mentions the rotate gesture though, people won't realize it exists otherwise.

**Comment by Adamantcheese** [comment]
There's a lot of things that need popup hints, I'll write that down in my notes as something to add.
