### ISSUE TITLE
Page numbers are missing

### ISSUE THREAD

**Issue by omgwtfbbqpls** [Adamantcheese/Kuroba#1030]
Page numbers are missing from the bookmarked thread sidebar, and also at the bottom of threads. Toggling the "Never show page number" option does nothing.

Using v4.13.6 on LineageOS 16.

**Comment by Adamantcheese** [comment]
Pages are displayed when available and are working correctly. It's possible that pages have either not been received, or there was an error parsing the JSON containing the pages, which would cause pages to not be available. Given that this is working on both stable and dev, I am going to say the problem is on your end. The "Never show page number" setting only applies to catalog mode page number display, which displays if the sorting order is not "Bump".

**Comment by omgwtfbbqpls** [comment]
Apparently this happens on some smaller imageboards - I've stopped using 4chan, so I didn't notice that it still works there.

**Comment by Adamantcheese** [comment]
Page parsing is currently only implemented on 4chan anyways. If you want page parsing on a different site, you can write the parser for it and submit a PR.
