### ISSUE TITLE
Question about sites not being available in app

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1070]
For a brief while, I couldn't access 4chan on Kuroba's latest release or dev release, though Clover and the mobile site worked fine. Other sites (though not 420chan) were available regardless. Is there a known reason why this could happen?
For example, 4chan's icon in the board select icon was not present when others were. Is there some behavior specific to Kuroba that would cause a delay in accessing the sites?

**Comment by Adamantcheese** [comment]
If 4chan's icon wasn't present, that means that the icon bitmap wasn't retrieved from the server. The icon's only ever retrieved once from the server and is held in memory. If it wasn't retrieved then that would indicate 1) the site was down or 2) the request failed and would need to be attempted again. Given that the site wasn't down from your experience, the request likely failed, which could indicate 1) your internet was just doing poorly or 2) something happened to the request inside OkHttp. There isn't behavior specific to Kuroba that would delay access to a site, that would be immensely stupid.

Once again, you seem to be having issues that are specific to you that haven't been reported elsewhere. I honestly am questioning your internet at this point because it's the only common item between all your reports. Maybe turning IPv6 or HTTP/2 off would help or something; Clover only uses HTTP/1.1.

**Comment by ghost** [comment]
My internet isn't bad at all, but I guess wifi is wifi. I'm not sure either.
