### ISSUE TITLE
Broken cross board >>> links

### ISSUE THREAD

**Issue by lasagnacrab** [Adamantcheese/Kuroba#1113]
Any >>>/ link throws an error "No applications were found to open this link". Is this a bug or is there a setting I need to enable for these types of links to work? Thanks!

Android 10
Kuroba v4.13.6
![20201006_112051](https://user-images.githubusercontent.com/67978700/95229516-48216800-07c6-11eb-99ac-f304065a5322.jpg)

**Comment by Adamantcheese** [comment]
Cross-board and cross-board search links work fine elsewhere, it's just the /mu/ sticky that has those setup by the moderator rather than the imageboard system, so they're processed like normal links. For reference, the top is what's in the sticky, and the bottom is what will usually be posted in a thread that is processed correctly.

```
<a href=\"/mu/catalog\"			     class=\"quotelink\">&gt;&gt;&gt;/mu/catalog</a>
<a href=\"//boards.4channel.org/mu/catalog\" class=\"quotelink\">&gt;&gt;&gt;/mu/catalog</a>
```
