### ISSUE TITLE
[Feature Request] Beta build without the leak detection code?

### ISSUE THREAD

**Issue by gut5** [Adamantcheese/Kuroba#1118]
Would it be possible to get something halfway between the dev build and the stable build? The leak detection kicks in so many times that it's destroying my battery.

**Comment by Adamantcheese** [comment]
Bit of a hack, but LeakCanary is patched out in CI before being built now with https://github.com/Adamantcheese/Kuroba-Dev/commit/2834de749c50680b150140af4c64d8e455c28553. I did it this way because otherwise the "proper" way (that is, changing the CI to build devRelease instead of devDebug) you'd have to completely uninstall the dev version and reinstall it due to mismatching signatures, but this way works just fine and doesn't cause any other issues.
