### ISSUE TITLE
[Feature Request] Fall back to Captcha when 4chan Pass fails

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#112]
Say you're logged in with a 4chan Pass and you switch networks. You need to wait half an hour before you can use the pass again. It would be convenient to automatically fall back onto Captcha if a 4chan Pass returns an error message rather than having to go into site settings and log out then re log back in later.

**Comment by Jamayyy** [comment]
I came here to suggest the same feature. I am frequently affected by this and wish Clover had this for years.

Today's update made this case even worse:
"The settings menu has moved from the left side slide panel from the bottom to the top, replacing the setup sites button."
Because of this change, you now have to do the following when switching from mobile network to wifi, or back:
_Swipe in from the left > Settings >Sites > Settings >Login >Submit > Back > Back > Back > Back_
You have to do this chain of steps to log out, and then again to log in. If you do this before the 30 minutes are over, it will say the pass is already in use by another user, and then you have to do it again later.

On a bad day, when going from 
_home wifi > mobile network > college wifi > mobile network > home wifi_
this would result in _at least_ 80 extra taps and gets annoying real fast.

Because of this I wanted to suggest an option "toggle pass" for the 3-dot menu in the top right of the app that simply logs you in or out and is only visible if you have a pass saved.
But even better would be if it simply fell back to captcha, if pass posting fails.

**Comment by Adamantcheese** [comment]
@Jamayyy you can open up the 4chan setup menu from the board select by tapping on the 4chan site itself, which will save some time, for now at least.

**Comment by Jamayyy** [comment]
@Adamantcheese thanks for the tip. It took me a while to find the button, because it's the last place I'd have looked at and I didn't know that UI element was "clickable". It's less of a problem that way, but captcha fallback would still be a great addition for any pass user.

**Comment by Adamantcheese** [comment]
I have no way of actually seeing what sort of errors are happening, so unless someone submits a PR I can't actually solve this.

**Comment by ghost** [comment]
It sends a message saying "This 4chan Pass is currently in use by another IP."

If it would help and if you have some way to contact you privately I can send you my pass details for testing.

An alternate method would be just to have a button to manually disable the pass for that specific post like Dashchan has.

**Comment by Adamantcheese** [comment]
This has been resolved as a result of a better cookie implementation being used in the app. You'll get the message once, and then you'll be able to post with authentication the next time you try to submit as you'll be automatically logged out.  For the future, these are the cookies that are sent to back as a result of a "this IP is in use" response. 
![cookies_pass_fail](https://user-images.githubusercontent.com/9031585/120876857-1e445f00-c568-11eb-9acb-d20449d5ce7a.PNG)
