### ISSUE TITLE
[Feature Request] Search option for thread history

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#1131]
The recent change of having the thread history on the drawer with the bookmarks is really nice, one downside however is that there no longer is an option to search through the history. Considering how large the thread history can get after a few days of browsing it can be difficult to find the thread you're looking for, so it would be nice if a way to search the history was added back.

PS. maybe also an "X" button to clear the history?

**Comment by Adamantcheese** [comment]
I'll see about adding in a search function for the drawer, for both pins and history (and whatever other adapter is loaded, if another one ever is put in there).
History is tied to the loadables in the database directly now, so "clearing" history won't really be a thing, but I can add a flag so that it doesn't display in history when loaded. History is currently set to load the last 250 loadables (as was the previous history implementation as well); I can reduce that down if that's too many.
