### ISSUE TITLE
[Feature Request] allow tapping on 404 thumbnails

### ISSUE THREAD

**Issue by PATXS** [Adamantcheese/Kuroba#1157]
not sure if it's just me, but i run into this old webm thumbnail issue #435 always, on vichan boards (tested on sushichan, lainchan, and wired-7, on both release and dev). arisuchan, as was mentioned in that issue, used vichan as well. as far as i know these are the only vichan sites supported by the app, and since the issue happens on all of them i assume it is no coincidence.

i see that at the time, the response to that issue was just a "wontfix". so, if there will be nothing done for this due to it being the sites' fault(all 3?), can we at least get an option to allow tapping on 404ed thumbnails? i checked, the webm is actually there every time, but opening them is really a hassle as it requires opening something else in the media viewer and then swiping to the webm of choice.

being able to just tap on the 404 thumbnail to open them would be much more convenient.

**Comment by Adamantcheese** [comment]
The reason is that webm thumbnails are not provided on vichan boards in an image format, but rather a single frame WEBM; for example, https://lainchan.org/player.php?v=/vis/src/1603947118493.webm&t=lainnoc.webm&loop=1 is the actual WEBM link, but https://lainchan.org/vis/thumb/1603947118493.webm is the thumbnail. I'll have it actually get the proper thumbnail.
