### ISSUE TITLE
File size limit unknown issue

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1164]
With files close to 4MiB it's apparently possible to go over the file limit despite the warning not appearing in the app and the file seemingly being small enough. I wonder if this could me a metadata thing? Or does the app factor that in when determining the file size, too? All I know is that windows explorer and my phone both list the file as 3.79 MiB, and that larger files up to 4 MiB work fine.

**Comment by Adamantcheese** [comment]
It's literally just using file.length(). If you can provide a sample image and the board you were trying to post on then I can investigate further, otherwise I'll just close this issue.

**Comment by ghost** [comment]
I did some testing and the conclusion I've came up with is that 4chan does something with JPEGs that it doesn't do with PNGs. It must ignore compression or something. Example given here with one that posts and one that does not.
https://files.catbox.moe/t69k6f.png
Here's the file that doesn't work if you need to see it, but I've confirmed the pattern with other JPEGs close to 4MiB
https://files.catbox.moe/dssk4x.jpg
The desktop site's warning about file sizes doesn't appear for either but only the larger file (at least as Windows and Android see it) is able to post.

Edit: I looked through my folders and it turns out I do have a JPEG larger than this from 4chan, and it still works so it's safe to assume nothing changed. Back to the drawing board, my only guess now is that somehow additional data is attached to the image that isn't being considered, or the issue is somehow specifically affecting some files and not others

**Comment by Adamantcheese** [comment]
I have reason to suspect that this is a 4chan specific issue rather than an application image. I can definitely confirm the same results as you, both on 4chan's site itself and in Kuroba with the second image. The file size being read in the application is the same size as what you'd have if you downloaded the image normally. I've submitted a bug report to 4chan's devs pointing to this issue, so hopefully they can resolve it. In the meantime, I guess you can always reencode the image in an attempt to post it. I know it's not a great workaround for like source-quality image dumping, but I don't think this is something I can resolve.
