### ISSUE TITLE
Report "Keyboard not showing up"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1174]
UUID: 030eb09df6dd21e72fcc588509b979d3
Build flavor: stable
Version name: v4.13.6
OS info: Android 10, sdk version: 29
Report description: 1. Search for something on the catalog
2. Press the 3 dots button, report
3. Close report form
4. Keyboard will not show up unless you go back and do another search

**Comment by Adamantcheese** [comment]
The keyboard appears just fine everywhere it is used. I'm gonna close this because I have no idea what this person is trying to report; their steps are inadequate for whatever issue they're trying to describe. Even just reading through the steps everything sounds like it works as expected. I guess they want the search to stay? That's not how the infrastructure works, a new Controller being presented will close the search, but since a new NavigationItem is being set as well, the old NavigationItem that holds that data for the search is discarded.
