### ISSUE TITLE
[Suggestion] scroll thread when opening reply menu

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1203]
There are a few quality of life tweaks I'd like to see, if possible.

It would be nice if the thread would scroll up/down to the post you tapped to quote when the reply menu opens, since it's no fun when it gets covered up by the keyboard or reply window.
Also, it would be nice when you're using bottom reply and you're at the bottom of a thread that it would scroll up when the menu is open. The app already does this for top reply when it would cover up the OP, so I think it makes sense.

**Comment by Adamantcheese** [comment]
1) Scrolling methods just scroll until something is visible on the screen. If you've tapped it, it's already on the screen so scrolling to it would do nothing.
2) It doesn't do that already; it allocates the space so that you CAN scroll and see the OP, but it doesn't scroll it automatically. The same goes for bottom input, it'll cover the bottom area of the thread, but allocate so you can scroll to see everything.

**Comment by ghost** [comment]
Well, nevermind then. I think I might be misremembering things.

**Comment by Adamantcheese** [comment]
There's no bug, that's how it's always been, even in Clover.
