### ISSUE TITLE
Report "[Urgent] Uploading Images"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1239]
UUID: a61ba4ec775bac609c46762df95f9849
Build flavor: stable
Version name: v4.13.6
OS info: Android 11, sdk version: 30
Report description: Since updating to Android 11 on my Samsung Galaxy S10+, the image upload option will no longer open the Gallery app. instead, it opens the 'Sound Picker' app, used for choosing ringtones.

This issue makes uploading images for posts and threads impossible, so a quick fix will be appreciated.

Thank You.

**Comment by Adamantcheese** [comment]
Sounds like Samsung's Gallery app is doing something different than it did before because Kuroba is following the guidelines provided here https://developer.android.com/reference/android/content/Intent#ACTION_GET_CONTENT. Not really surprised, but I honestly can't do anything about it when we're already trying to get the most generic content possible.

**Comment by K1rakishou** [comment]
I think that using a "Show alternative file pickers" setting may help.

**Comment by Adamantcheese** [comment]
It already exists in Behavior > Other Options. I can't help though if it's short circuiting the boolean check for the setting and the Sound Picker app really is the only thing that can open a file.

**Comment by K1rakishou** [comment]
Yeah I know. I wrote that message in case that the person who sent the report reads this issue.
