### ISSUE TITLE
.PDF files are downloaded without warning in a non-temp location

### ISSUE THREAD

**Issue by alexbrenvero** [Adamantcheese/Kuroba#1263]
Since the last few dev updates, selecting a pdf automatically opens a web browser which will then download the pdf to the default download location.
This makes the image gallery mode essentially useless on /tg/ since there are so many pdfs alongside pictures.

**Comment by Adamantcheese** [comment]
Right now I've got it set so that "other" images, like PDFs, will automatically attempt to open up in an associated application. It sounds like you've got yours set to open up in a browser or it's the only thing that handles that type of link, and since it doesn't know how to display the PDF it just downloads it to your download location. Would it be preferable to have the app show a snackbar or something requesting if you want to open the file up?

**Comment by alexbrenvero** [comment]
> Would it be preferable to have the app show a snackbar or something requesting if you want to open the file up?

Seems like a good idea.
