### ISSUE TITLE
Hiding threads no longer makes a stub on catalog

### ISSUE THREAD

**Issue by calactic** [Adamantcheese/Kuroba#1270]
As subject, when hiding a thread, all that happens is the image goes away and the thread subject moves up, but the size of the post itself doesn't change.

Dev release :  v4.13.6-d80cc170

**Comment by Adamantcheese** [comment]
CardPostCells have been split into a Stub and regular variant just like how PostCell and PostStubCell exist. I tried to keep them visually similar to before the split, so could you emphasize what you're expecting to occur? If you don't want it to be there anymore you should use Remove instead of Hide, which eliminates it entirely from view.

**Comment by calactic** [comment]
The way I use hide/remove varies between boards and it's more for my personal organisation, but as an example, I was expecting the shrinking behaviour that happened in previous versions as seen in the bottom image. 

![Screenshot_20210522-194632](https://user-images.githubusercontent.com/78216797/119237994-c9e8ba80-bb37-11eb-8280-ca02d74c8457.png)
![Screenshot_20210522-194655](https://user-images.githubusercontent.com/78216797/119237998-cce3ab00-bb37-11eb-8839-ef177779671d.png)
