### ISSUE TITLE
Board links highlight, but do not function with alternate text styles

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1271]
For example, the /r9k/ sticky that links to /soc/. You _can_ click on it in the app, it just says "No applications were found..." because it's using big text.

**Comment by Adamantcheese** [comment]
There are two stickies in /r9k/ with a /soc/ link, one that is `<a href="https://boards.4chan.org/soc/">/soc/ - Cams &amp; Meetups</a>` and another that is `<a href="/soc/" class="quotelink">&gt;&gt;&gt;/soc/</a>`. The second one is the one that is failing because it doesn't line up with all the other quotelinks on the site, probably because it was manually input by a moderator.

Possible stuff throughout the site for board hrefs include:
https://boards.4chan.org/soc/
/soc/
//boards.4chan.org/soc/

**Comment by Adamantcheese** [comment]
They should all redirect in-app now rather than attempting to open it as a link.

**Comment by ghost** [comment]
Hey, cool
