### ISSUE TITLE
Report "Mute when earphone on"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1277]
UUID: 1718792f724ead8141fd0c79e89d096f
Build flavor: stable
Version name: v4.13.6
OS info: Android 10, sdk version: 29
Report description: Mute videos is ON and mute with headphones is OFF

But the audio is still muted whenever I open a VIDEO using headphones. No idea why.

Already tried switching both options on and off

**Comment by Adamantcheese** [comment]
Either this person has a bluetooth headset and is misinterpreting the headphones text (it specifically calls out WIRED headphones), or their ROM is being stupid with audio devices like the emulator, which doesn't change the available output devices to have an extra one for a virtual headset when you toggle that option. It otherwise works fine on my device.
