### ISSUE TITLE
The way posts links are highlighted is weird

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1280]
The behavior of highlighting links to a post is nice, but it only applies to replies that mention more than one, leading to inconsistencies. Also, I think it's unpleasant that the bold text is slightly wider than normal text. Shouldn't just a color change suffice?

![Screenshot_20210526-051656.png](https://user-images.githubusercontent.com/30278765/119731472-9a3df900-be3c-11eb-959c-a889c1e95e68.png)

In this example I think it would be better if all the >>556992862 links were displayed the same way, in light blue.

**Comment by Adamantcheese** [comment]
Bring it up with @Safrone, they wanted it changed in #1232. Both of you together should come together and come up with an appropriate solution for highlighting links. Clover only changed the color and all the same links were colored. I changed it so that links were also bold when I did theme changes so they were more visible. In response to #1232 I changed it so that links would only appear highlighted if there was more than one quote in a post and they would appear slightly wider. I thought this was a good compromise since bold, wide text in every post was quite ugly, but still made appropriate distinction where needed.

If a setting should be added for some sort of better display, tell me.

**Comment by ghost** [comment]
My opinion is that all quote links to the same post should look the same in any given instance. It's better to make the non-relevant ones look muted in comparison.
Other than that, I don't like the bold but I can live with it if that's the best solution. 

Edit: perhaps revert to clover's behavior, and add an option that highlights these currently bolded posts? Or maybe place a marker next to them?

**Comment by Safrone** [comment]
I agree it should be consistent, in general the marked link should be "brighter". Looking through the themes it looks like Light, Photon, Neon have the marked link "darker" (more muted as @clawyf says), Colorblind and Yotsuba the link colors are different colors so maybe less of an issue. My thought for a clearer highlighted link was due to my reaction to the idea that the marked link should draw attention to it (mainly by being brighter than unmarked links). Or something like what is done on the website where the marked link is changed from underscore to dashed underscore. IDK if that's hard to implement for whatever reason but I think it's less obtrusive overall. 

![image](https://user-images.githubusercontent.com/14047377/119832768-7c1fd980-becc-11eb-84d0-0aca1ace8673.png)
