### ISSUE TITLE
Highlighted posts don't show reply counts 

### ISSUE THREAD

**Issue by HamletDuFromage** [Adamantcheese/Kuroba#1285]
On Kuroba-dev 4.13.6 6e5e16b

I have a filter for keywords that highlights posts (and those show their replies properly) but the replies on that post don't show their own replies.

In this picture >>338355036 replies to a post that got highlighted by my filter, is itself highlighted because it's a reply of it, but when I quoted it, it doesn't show "1 reply" under it

![Screenshot_20210606-033550.jpg](https://user-images.githubusercontent.com/61667930/120909742-6eaae200-c678-11eb-9083-5a52345bc15e.jpg)

It does show it in the pop up however

![Screenshot_20210606-033737.jpg](https://user-images.githubusercontent.com/61667930/120909752-8e420a80-c678-11eb-9628-2f7d5d9890a2.jpg)

Thank you for your work btw, the app is amazing and I can't believe it took me so long to learn about the dev releases

**Comment by Adamantcheese** [comment]
I'm not sure if you have any posts being removed from the thread or filter removed or anything, but with only a highlight filter on, set for /strobechad/i and applying to replies, nothing appears wrong. It may be that post removal is messing with stuff and I need to fix that; I already spotted an issue with PostsFilter not correctly being applied in post popups, since they aren't a "full thread".
![image](https://user-images.githubusercontent.com/9031585/120918691-89765a00-c66a-11eb-9f87-373bc8379969.png)

**Comment by HamletDuFromage** [comment]
No, I have a filter for `/AIO/i`
I don't have any removed post either. Ultimately it's not that big of a deal, but it struck me as odd

See this video here, it might be clearer: https://streamable.com/fib6im

![Screenshot_20210606-144343.jpg](https://user-images.githubusercontent.com/61667930/120924785-a5fbac00-c6d5-11eb-9ee7-30967c542bc5.jpg)

**Comment by HamletDuFromage** [comment]
Also post >>338362528 got a (You) that doesn't show either. Seems like the whole reply chain has that issue.

**Comment by Adamantcheese** [comment]
Weird that this issue didn't show up in my testing, I appreciate you showing me your filter, this should be fixed now.

**Comment by HamletDuFromage** [comment]
Sweet, thank you for the fix and sorry for the poor wording in the OP
