### ISSUE TITLE
[Feature Request] Multiple Filter Highlights per Post

### ISSUE THREAD

**Issue by dzamie** [Adamantcheese/Kuroba#1297]
Would be nice to have multiple colored bars to indicate when a post has tripped multiple highlights (e.g. filters as /dog/:red and /cat/:blue, so a post that says "cat dog" gets a red line and a blue line).

I can't search forks, so I'm having a hard time figuring out where highlights work in the code here. I do understand if it's based on a "margin" attribute like what 4chan-X does, rather than its own object in a layout, and is therefore not feasible to implement.

**Comment by Adamantcheese** [comment]
Currently multiple highlight filters acting on the same post will be processed in-order by the filter engine, so the last filter in your list will be the one that applies. In that manner, it's kinda like a priority system for highlights where lower filters in the list will be the final color.

Posts only have a single highlight view right now; I could instead add an option that highlights the specific post text in a user-chosen color rather than a bar on the side, kinda like how filter debugging is currently implemented on dev.
