### ISSUE TITLE
Slider Disappears

### ISSUE THREAD

**Issue by uckthis** [Adamantcheese/Kuroba#1308]
When captcha is loading, the slider is there, but when it's loaded, slider disappears. What do?
![Screenshot_20210714-120858](https://user-images.githubusercontent.com/28671050/125578952-72f28bcc-aeea-435d-b895-a520f547ac96.jpg)

**Comment by Adamantcheese** [comment]
The new captcha comes in 3 forms: slider, no slider, and free verification. Usually a slider one will be presented, however if a non-slider one is returned by the server, the slider will be hidden from view. You've gotten a non-slider one, so just enter the text and be done with it. I'll change it so that the slider is hidden by default to start.
