### ISSUE TITLE
Can't use 4chan pass

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#1309]
I get this message when trying to post, even though I'm using a pass. When I switch to CAPTCHA, it still happens.
![Screenshot_20210716-114334.jpg](https://user-images.githubusercontent.com/30278765/125988417-4585c7da-0898-486e-b18b-062749f1bbbf.jpg)

**Comment by ghost** [comment]
Something with my cookies is fucked, even the report menu doesn't know I have a pass now

**Comment by ghost** [comment]
Having the pass signed in causes the issue.
Please fix
Edit: I think I should clarify that captcha works now that I cleared app data and imported settings again

**Comment by ganderson04** [comment]
I'm also facing this issue, but only on SFW boards.

**Comment by Adamantcheese** [comment]
Yup, some previous behavior that I was relying upon got fixed site-side, notably that logging in would return a cookie for both the 4chan and 4channel domains, but now it looks like they have separate (but identical in function, other than returned cookie domains) webpages. Well, at the very least I can fudge the cookies app-side to have them never expire as opposed to the single-day their specified lifetime was anyways, since 4chan accepts expired cookies.

**Comment by ZenythFactor** [comment]
Please fix soon
I don't wanna use slow ass Clover again

**Comment by ghost** [comment]
> Please fix soon I don't wanna use slow ass Clover again

If you aren't on the dev branch you definitely should be
