### ISSUE TITLE
[Question] Fdroid Packaging

### ISSUE THREAD

**Issue by Nutjob** [Adamantcheese/Kuroba#134]
Hi, i've submitted a request for packaging Kuroba on Fdroid a couple of weeks ago, now i'm being asked if you are fine with it.
You can have a look over [here](https://gitlab.com/fdroid/rfp/issues/1010).

**Comment by Adamantcheese** [comment]
Given that a) this has an auto updater which immediately invalidates it for F-Droid (and Clover too for that matter, but Clover's update API isn't publicly visible code-wise, which says a lot about how thorough they are about submissions) and b) this app is unstable enough as it is with all the new features being added, I'm going to say no.
You are free to fork the repository and submit your own fork yourself, but not this one.

**Comment by Nutjob** [comment]
Ok, i've notified the packaging team of your decision.

**Comment by IzzySoft** [comment]
@Adamantcheese unless the auto updater is proprietary / blob, I don't know where you got that idea from (Tower Collector also has an update checker/installer included and is on F-Droid). But Clover somehow rings a bell (vaguely remember there were issues with that). As for unstable, the description could point that out and all should be fine – one day you hopefully "achieve stability".

Just saying. Of course your decision will be honored. So thanks for speaking out and including your reasons! I'm afraid at least the Clover part will stand, even if you could be convinced otherwise on the other points…

**Comment by namazso** [comment]
@Adamantcheese are you still sure about this decision? there's now a slower and more regular update cycle, the app is far more stable, etc..

**Comment by crisalis2** [comment]
@Adamantcheese @IzzySoft 
How about just letting the well-known IzzyOnDroid repo host your release APKs?
https://apt.izzysoft.de/fdroid/index/info

**Comment by Adamantcheese** [comment]
If they add it, whatever. Do whatever you want with the APKs.
