### ISSUE TITLE
Cannot click upper part of thread partially appearing at the bottom of thread list

### ISSUE THREAD

**Issue by c933103** [Adamantcheese/Kuroba#1340]
Video on how to reproduce until ultimately successful clicking the thread: https://youtube.com/shorts/fH5wcU8MOVw

Phone is Xperia 10 III with 21:9 screen and Android 11
Kuroba version on latest stable.

**Comment by Adamantcheese** [comment]
Working fine for me, you can try dev to see if I randomly fixed it doing other stuff. Also what the hell is this youtube link, I haven't seen one like this before.

**Comment by c933103** [comment]
> Working fine for me, you can try dev to see if I randomly fixed it doing other stuff. Also what the hell is this youtube link, I haven't seen one like this before.

Confirm cannot reproduce on dev branch
But when will it get into stable branch?
As for the YouTube thing, that's the first time I saw it too, I didn't touch any setting, probably that's YouTube's response to TikTok and would activate once it deemed a video being too short?

**Comment by Adamantcheese** [comment]
Whenever dev is stable. Right now that means fixing the image loading issue and finishing up any remaining captcha issues, I think. I'll also adjust the youtube embedder regex to pick up that style of youtube link at least.
Closing since it's fixed but I don't really know what I did to fix it or when.
