### ISSUE TITLE
[Question] Opening non-image files

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#136]
4chan allows pdf files on /tg/ and various other chans allow non-image formats — is there a way to open/view them in Kuroba?

Currently it gives me a "Failed to show image, deep-zoom loading failed" error message when I try, so I revert to opening them in a browser.

**Comment by Adamantcheese** [comment]
Currently PDF files are treated like images, which is why you get that error. Unfortunately I have no way of actually determining that it IS a PDF, as the file cache doesn't hold onto that data, and no probing library actually seems to probe, all of them return null for the MIME type. The best I would be able to do would be to automatically open up the appropriate application to handle it, but alas, because of the lack of a file extension (and no, I can't just slap any extension on it, that's bad practice for the cases where it's not a PDF at all), I can't do anything about it.
