### ISSUE TITLE
[Question] Menu text bold

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#148]
Was it intentional to remove all bolded text from menus in the last update or is this just a bug with the new font stuff?

**Comment by Adamantcheese** [comment]
The Roboto-Medium font is now pulled from your system rather than being distributed from the app, as it was the one responsible for menus and other "title" like text. It's possible that the Roboto-Medium.ttf that was previously bundled with the application wasn't correctly labeled and was actually Roboto-Bold or Roboto-Black. I'll take a look at it.

**Comment by Adamantcheese** [comment]
The previously distributed version of Roboto-Medium with the app is version 2.000980 from 2014. The most recent Google distribution is version 2.137 from 2017, which is slightly smaller and thinner than the previous version, but is otherwise the same thickness; this version should be what is distributed with most phones now. I can change it to be Roboto-Bold instead, which would make it look better.

**Comment by Pentaphon** [comment]
@Adamantcheese yes, please

**Comment by ownBard** [comment]
Alright, thank you.
