### ISSUE TITLE
Option to notify user on startup when there's a new version on Github.

### ISSUE THREAD

**Issue by Pentaphon** [Adamantcheese/Kuroba#149]
Considering there will be no F-Droid entry for this and F-Droid is a slow means of updating apps anyway, can we have an option to notify the user when there is a new Kuroba update?

I suggest the following:

1) Add an option to the settings (behavior) menu to notify the user on startup. 
2) Disable this option by default so it doesn't bother people who don't want every update.
3) Show a notification that when tapped, brings up the current update window with changelog. 
4) From there, updating works the same way as it does now. 

Newpipe already does this if you want an example. 

https://github.com/TeamNewPipe/NewPipe/pull/1608

**Comment by Adamantcheese** [comment]
The app already notifies if there is a new update on app startup. There is a delay of 5 days before doing another update check if there is no new version, which is why the manual button exists. Pretty much everything about the auto-updater works like it did in Clover, I've just modified it to pull from Github Releases and pull all necessary info from a release to present to the user, as opposed to Floens' API method that nobody had access to besides Floens.

**Comment by Pentaphon** [comment]
>There is a delay of 5 days before doing another update check if there is no new version

@Adamantcheese Ah, that's why I didn't know. Sorry. Thanks for your work.
