### ISSUE TITLE
[bug] Post watcher number in italics though thread hasn't reached bump limit

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#162]
![Screenshot_20190701_221315](https://user-images.githubusercontent.com/50524977/60476174-e41e0480-9c50-11e9-9b80-f38dc2e35995.jpg)
https://boards.4chan.org/an/thread/3068891#p3068891
Sometimes happens.

**Comment by Adamantcheese** [comment]
It should update when the thread gets updated, or you can try toggling it's watch state to force an update. I honestly have no clue what the hell this recycler view is doing at this point because it refuses to ever update. I have one idea for what to do if that doesn't work.

**Comment by Astridchan** [comment]
Can confirm this bug. There is also some weird behaviour happening when toggling the watch state, where the thread post count will alternate between being italicized and un-italicized.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/40862101/60524263-ec2f8000-9cf4-11e9-91c7-6c60d5503ff5.gif)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40862101/60524264-ec2f8000-9cf4-11e9-95ce-63c8890fbecc.gif)

**Comment by Adamantcheese** [comment]
At this point I know it's the recycler view doing weird shit. If you tap on it enough times, or another item enough times, it'll magically render itself unitalicized. Going to that thread though, and some other random one will now be italicized. I'll see if I can just replace the recycler with something else because this is really dumb.
