### ISSUE TITLE
Importing settings failed, returned error

### ISSUE THREAD

**Issue by TacoTheDank** [Adamantcheese/Kuroba#19]
![Screenshot_20190603-173133](https://user-images.githubusercontent.com/32376686/58836090-b29c2400-8625-11e9-9c7f-8d66cab7cd3c.jpg)

Got this while using the guide to migrate Clover to Kuroba. Well, the guide worked fine, but attempting to import from your latest Clover build [4681c89] into Kuroba 4.0.7 gave me this. Here's the json file: https://mega.nz/#!xe5nAaIQ!L1Xujjn82-wsW0mz3tsgwwXlfPWbNcrFkQ9VL5Iuibs

**Comment by Adamantcheese** [comment]
This json file is malformed, and was produced prior to the fix [in this commit.](https://github.com/Adamantcheese/Kuroba/commit/9b47d5e9cafbd7e00b9d32753425575a9c33b81c) You can attempt to salvage it by removing the malformed entries manually, but the text in other entries will likely be fucked up. This was caused by 8chan having weird shit in the names and descriptions.

**Comment by TacoTheDank** [comment]
Ah ok. I wasn't really worried about not having the threads transferred, because I have both apps installed. I'll just go through all the ones in the Clover one, then uninstall it, and start anew in Kuroba.

Btw, where did Floens say he didn't want to merge PRs (according to the README)? I only see that he's inactive on the main branch (and pulling translations for the i10n one).

**Comment by Adamantcheese** [comment]
He never said anything. His inaction is the unwilllingness. The i10n branch is auto updated by Crowdin, not Floens, but uses his account via a Github integration.
