### ISSUE TITLE
[Bug] Regression in gallery mode

### ISSUE THREAD

**Issue by happapa** [Adamantcheese/Kuroba#198]
Since updating to 4.4.3, performance of the image gallery mode has taken a major hit. After opening any thread with many replies (and images) and immediately starting the image gallery view, thumbnails load significantly slower than before, tapping an image can hang the app for several seconds and even scrolling down the list can cause the app to lag. Also, the thumbnails appear to be much better quality than before, so maybe this has something to do with it? I do not have image prefetch enabled and trying this on two different devices gave me the same results.

**Comment by Adamantcheese** [comment]
Images are no longer scaled down on load. The image returned from the downloader is the full size image rather than a rescaled version. Previously images were rescaled down to the thumbnail size, which made them very blurry and sometimes unrecognizable (basically 250x250 images). Since these images aren't fed through the regular file cache, they may be released and redownloaded as you scroll. Currently this limit is set to 1/8 the size (in MB) of the runtime memory.

**Comment by happapa** [comment]
Do you see the the performance drop on your own device? If the choice is between the current implementation and the old one with blurry thumbnails, I'd personally revert the changes without a second thought. Some people in the /g/ threads have also been saying that they experience crashes in the gallery mode when there are many images, which sounds related.

**Comment by Adamantcheese** [comment]
It's specifically an issue when the images are all very large. The previous implementation (i.e. Clover) had them being rescaled on load to that smaller image, which was then cached. I've bumped it up to 500x500, but the other resolution upgrades will remain. On a phone, gallery mode images should appear high quality now without the performance hit; the reason for the blurriness before was actually due to upscaling to match the image view's dimensions; that is to say, the loaded image after it's rescale was about 250x250, but the image view's dimensions were (on a 1080 width device) 360x360, which meant it had to upscale the image and made it blurry.

**Comment by Adamantcheese** [comment]
Note that image that are less than 500x500 in dimension will be loaded as a full image still. Images that are smaller than the dimensions of the image view will be upscaled by the image view itself to fit, which will make them blurry.
