### ISSUE TITLE
Unusably slow

### ISSUE THREAD

**Issue by namazso** [Adamantcheese/Kuroba#215]
Certain actions became unbearably slow with the recent update.
Simply removing a thread from watcher can take up to 10-20 seconds of UI freeze.
I have more than a hundred or so threads "watched" (about all but 20 are dead), in case it matters

edit: simply scrolling a thread causes such freezes
edit2: seems to happen when thread updates

**Comment by K1rakishou** [comment]
This thing is not easy to reproduce. I think this may happen because of the disk being actively used by other threads or even other processes which makes every access to it times slower. What we need to do is to move the ImageLoader.getFromDisk() method from the main thread to a background thread. There may be other methods that use disk apis on the main thread.

**Comment by namazso** [comment]
Not sure what you mean by not easy to reproduce. While I didn't try, I'm pretty sure adding a moderately high amount of threads to watcher should probably reproduce this, and as I said the freezes are very significant, easily over the time when Android displays "Kuroba is not responding", compared to at most a few miliseconds in 4.4.4.

**Comment by K1rakishou** [comment]
I tried adding like 50 pins that were both watching and downloading posts and had no lags. But then couple of times I scrolled the catalog, right after reinstalling the app when there we no pins, and it lagged like hell. But even in this case there we no lags that would cause ANRs (which happens after like 5 seconds). They were like micro stutters, 30-70ms each and were happening only while scrolling. I tried using the profiler but seen nothing unusual there probably because the cause was, like I already said, in the native code (the File API).
