### ISSUE TITLE
[Feature Request] Fullscreen image viewer

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#22]
Make it possible to view images (and videos) in fullscreen by hiding the Kuroba UI, status bar and the navigation bar. Fullscreen mode could be toggled by a button in the toolbar (example 1.), or tapping on the image in while the image is opened (example 2.). Since tapping on an opened image currently closes it in Kuroba, this behaviour should be changed so that tapping on the image itself toggles fullscreen mode, whereas tapping outside of the image closes it.

![fullscreenmode2](https://user-images.githubusercontent.com/40862101/58899484-b8693680-8705-11e9-9021-ebcdfdfb682b.png)

**Comment by ownBard** [comment]
>Since tapping on an opened image currently closes it in Kuroba, this behaviour should be changed so that tapping on the image itself toggles fullscreen mode, whereas tapping outside of the image closes it.

Yes, I'd like something to be done about this. It's too easy to accidentally close images while trying to zoom in or swipe (especially since I prefer to use one-handed zoom and especially since zoom only works after the full resolution image has loaded). It's also a bit counter-intuitive when compared to gesture controls of most image gallery apps.
