### ISSUE TITLE
New Save thread icon?

### ISSUE THREAD

**Issue by darkDaiyo** [Adamantcheese/Kuroba#223]
Current one looks out of place. What happened to previous icon i saw on /g/? It was similar to Overchan's save icon.

**Comment by K1rakishou** [comment]
I asked people to draw one but no one did so I drew one myself. You are free to draw a new one but it should be vector. 
The animation contains 6 xml files ic_download0.xml, ic_download1.xml, ic_download2.xml, ic_download3.xml, ic_download4.xml and ic_download5.xml you can find them here https://github.com/Adamantcheese/Kuroba/tree/multi-feature/Kuroba/app/src/main/res/drawable

**Comment by Astridchan** [comment]
Sorry, I know nothing about creating vector graphics so I can't help you with a new icon, but IMO the existing icon only needs a few small changes to make it look less out of place:
1. Make the icon displayed by default (ie. when not downloading anything) filled in rather than outlined
2. Make the icon height align with the other icons
3. Make the icon corners slightly rounded/curved (as with the other two)

![Screenshot_2019-07-22-14-24-24-313_com github adamantcheese chan](https://user-images.githubusercontent.com/40862101/61630972-c95c1000-ac91-11e9-9eda-64884aa3456a.png)

**Comment by ownBard** [comment]
There already exists a download icon as @Astridchan describes being used in the image viewer but it's just in png files.
