### ISSUE TITLE
Local thread saves from an already archived thread are never "fully downloaded"

### ISSUE THREAD

**Issue by Adamantcheese** [Adamantcheese/Kuroba#227]
If you open up a thread from 4chan's archive via the catalog menu button, open up a thread, and try to locally download a thread, it never reaches the "finished" state. You can tell because with the most recent change for the animated vector drawable for the save icon, it never actually stops animating, and breakpoints show me that it never reaches that state.

**Comment by Adamantcheese** [comment]
Unless of course this is intentional as threads in the archive aren't 404'd, however if they're archived you should still consider them completed as nothing more can be downloaded.

**Comment by K1rakishou** [comment]
The download button shouldn't be visible when viewing an already archived thread because it's not supported right now. I guess there is a little window when a thread gets archived but we still didn't check whether it's archived or not so the button is visible and you can start the download. I guess it will be easier to just support the ability to download already archived threads.
