### ISSUE TITLE
[IMPROVENENT] Manual update of Thread watcher

### ISSUE THREAD

**Issue by Datasnuten** [Adamantcheese/Kuroba#233]
The update interval on the thread watcher may be considered too high. I think some manual method to update the watcher would be beneficial. Perhaps by scrolling the list down when top element is already shown.

**Comment by K1rakishou** [comment]
What do you mean by thread watcher? The pin watcher that shows new posts in the pins list? Or the thread downloader? Or the thread current page watcher?

**Comment by Datasnuten** [comment]
I'm referring to the thread watcher watching bookmarked threads, which is enabled by the first "Thread watcher" option in the option menu. 

An alternative to manual updating could be another thread watcher setting, to set the update interval.

**Comment by K1rakishou** [comment]
Well there three types of intervals now. 
1. If you only have pins that watch new posts then the interval is as it was before - 15 seconds.
2. If you have both pins that watch threads and pins that download threads then the interval is 60 seconds.
3. If you only have pins that download threads then the interval is 180 seconds.

If you only have pins that watch threads, then 15 seconds is not that much I would say. Maybe we could improve intervals to always use old time (15 seconds) but update pins with different flags separately. Because right now if you have 15 pins that watch posts and one that download them then all of them will be updated once a minute instead of only the one that download threads being updated once a minute and the rest once in 15 seconds.

**Comment by Datasnuten** [comment]
I understand you think a 15 second interval is enough, but would you accept a pull request with a manual update implementation, or a setting which allows the user to change that time? Or is it superfluous in your opinion?

**Comment by K1rakishou** [comment]
There is no point in making the interval shorter than this because 4chan servers do not send you updated content on every request like it was before, there is like 15-20 seconds delay.
