### ISSUE TITLE
[BUG] Can't remove a 404'd thread from bookmark by pressing the bookmark icon

### ISSUE THREAD

**Issue by ayy91** [Adamantcheese/Kuroba#248]
![ezgif-5-60fb28541e2d](https://user-images.githubusercontent.com/51542078/61998626-58ff2580-b0bb-11e9-818b-01588b51a334.gif)

**Comment by floppyD** [comment]
Can confirm

**Comment by K1rakishou** [comment]
Actually you are not supposed to do it. The thread is deleted so we don't have any information about it thus we can't unpin it from that menu. Those buttons probably should not be visible when a thread is 404ed. But you can use the pins list, yes.

**Comment by Sextallone** [comment]
I have created an account just so I could report this bug. Glad to see someone has already created it. I can't stand this bug anymore.

> Actually you are not supposed to do it. The thread is deleted so we don't have any information about it thus we can't unbookmark it from that menu. Those buttons probably should not be visible when a thread is 404ed. But you can use the bookmark list, yes.

@K1rakishou: That's flawed logic with zero common sense. I understand there is a technical obstacle, but for the end user this sounds ridiculous. Imagine this: you've bookmarked a website on Google Chrome, the website is permanently shutdown and now you can't remove it from your browser bookmarks.

I seriously doubt you have zero information to remove the bookmark on Kuroba. First of all, the entry is still there. So if there is data, you can track it and remove it. Second, if you ask Kuroba to clean all bookmarks by touching the X button, the dead bookmarks will get removed too. But that's not a solution, because if I'm annoyed a 404 thread is bookmarked, I only want to remove the 404 thread. I do not want to lose all of my 15 other bookmarked threads I'm keeping track of too.

So what's pending here is finding a way to better connect the bookmark button to the bookmarks list. Make it so it does not rely on online/Internet data. Make the button remove the entry locally, offline. Only then you'll solve the bug. And please, do solve it! This bug such a pain for autists like us who like to organize and keep our shit clean. 

Thank you guys for your great work.
Kuroba is the best imageboard app currently.

**Comment by Sextallone** [comment]
My bad. This issue is not as bad as I thought. Because as OP has shown us, you actually can selectively remove a bookmarked 404'd thread by swiping the entry to the right on the list.

Though, this is obviously still a problem, because the existence of a non-working bookmark button fooled me into thinking there was no way to remove a 404'd thread from the list.
