### ISSUE TITLE
[BUG] Thread watcher doesn't update post numbers for archived threads

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#257]
Issue summed up by anon:

\>post in or bookmark thread
\>close app
\>come back later
\>thread is archived
\>[unread] post counter says 0 and is grayed out in the sidebar
\>open thread anyway
\>50 new posts

Also, in some situations, archived threads will only display 0 / 0 and never update.

Steps to reproduce:
1. Have archived threads bookmarked.
2. Crash the app from dev settings.
3. Upon reopening the app, archived threads will display post count as 0 / 0 until you open each individual thread.

PS. I notice the archived thread icon ![archived@2x](https://user-images.githubusercontent.com/40862101/62155666-2438db80-b312-11e9-9092-7eb3f3ca30b3.gif) is gone from the bookmark list, was this change intentional?

**Comment by Adamantcheese** [comment]
When you close the app, all of the thread information is gone, because that isn't saved in any database. If you're seeing older numbers, that's a feature of Android saving the state of the application; it should default to 0/0 because there's no information about that thread anymore.

I'll double check the archived thread icon. I didn't mess with that code after I made the change a while back to move the icon to the front of the text for visibility reasons.

**Comment by Adamantcheese** [comment]
I'm assigning this to @K1rakishou, as is seems that the thread saving has something to do with this. The status cell at the bottom of the thread properly gets the correct thread, which has the status for it being closed and archived, however the pin status cell doesn't, and it says that the thread isn't closed or archived, which is why the icon isn't appearing, despite the thread actually being archived. It's being sent to WatchManager's onChanLoaderError function, which it really shouldn't be.

**Comment by K1rakishou** [comment]
That's because I marked archived threads as deleted (404) so that I could figure out when stopping downloading them. So the pin that is associated with the thread would never have "archved" flag == true which is needed for that icon to be shown. It should be fixed when https://github.com/Adamantcheese/Kuroba/pull/247 is merged since I added the ability to download already archived threads.

**Comment by Astridchan** [comment]
@Adamantcheese:
I noticed that when you crash the app and reopen it, the total reply count resets to 0 for all bookmarked threads (until thread watcher updates them again), but the app does seem to remember the unread post count and the scroll position in a thread since those don't reset between app closes. Is that information getting saved to a database? If so, then maybe the thread information for archived threads should be saved too, since having archived threads display as "0 / 0" isn't really ideal. Alternatively, you could have the thread watcher update archived threads once when the app is opened for the first time after being closed (since it obviously wouldn't make sense to update them every 15 seconds).

**Comment by Adamantcheese** [comment]
I'll double check the actual stuff it's pulling and give you a proper answer.

**Comment by Adamantcheese** [comment]
Pins save, in the database, a last count of replies in the thread, and a new count as well, which is what's displayed. The actual total number of replies in the thread is always the watchNewCount minus 1 for the OP, so I'll change it to be that instead of calculating the thread size.
