### ISSUE TITLE
[REFACTORING] Make PinWatcher store posts in the database instead of the memory

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#272]
I've pinned 57 threads each with 200-300 posts and the result is almost 12 MB of memory allocated just for posts that we don't even need to always be in the memory. 

![profiler](https://user-images.githubusercontent.com/10332458/62424661-99256000-b6da-11e9-9225-0dd1626ce628.png)

Of course this is causing the GC to clean up the memory.

![unknown](https://user-images.githubusercontent.com/10332458/62424663-9dea1400-b6da-11e9-80ea-91da53765fa0.png)
![unknown (1)](https://user-images.githubusercontent.com/10332458/62424665-a3475e80-b6da-11e9-8888-1d238dc373ab.png)

**Comment by Adamantcheese** [comment]
Please for the love of god don't waste engineering effort on this. 12MB is not enough to care about and would basically mean your entire thread saving feature went to waste on some other implementation rather than using the database outright. In addition, GC is only running for, at a most, .5ms, which is basically imperceptible. And to top it all off, the BitmapLRUCache is definitely using WAY more memory over the lifetime of the application, as it uses a maximum of 1/8 of the current runtime memory (for the 512MB you have allocated here, that's still at least double what the pins take up).

If you submit a PR for this I won't merge it.
