### ISSUE TITLE
[Suggestion] Reply layout change

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#275]
With the addition of the new Captcha button, the horizontal green line in the reply layout is now kind of weirdly positioned, leaving quite a large amount of empty space below it:

![replylayout](https://user-images.githubusercontent.com/40862101/62474484-a78f7c80-b7ab-11e9-8421-dd0998023347.png)

The simplest solution would be just to to move the line lower:

![replylayout2](https://user-images.githubusercontent.com/40862101/62474755-474d0a80-b7ac-11e9-9a88-a5e48bf8981f.png)

Alternatively, you could make use of the empty space and move the text options (">" caret, code and spoiler tags etc.) from the expanded reply layout there so they are easier to access:

![replylayout3](https://user-images.githubusercontent.com/40862101/62474866-8b400f80-b7ac-11e9-8c61-11fcc51756c4.png)

**Comment by floppyD** [comment]
That last one looks nice. I think that switching the recaptcha button with the post button or the media button would make it look even better since media and post have the same design and they look good together.

**Comment by ownBard** [comment]
@floppyD I disagree, I prefer having the media button further from the post button so I don't have to be so precise about pressing the right one.

**Comment by floppyD** [comment]
I don't see how you would press the wrong button, unless you have some motor disorder or if you have fat sausage fingers (in this case the solution would be eating less burgers), but ok. No one ever complained about the old placement, which is exactly what I'm suggesting.

**Comment by ownBard** [comment]
@floppyD Please calm down before you hurt yourself. There's nothing wrong with my preference.

**Comment by floppyD** [comment]
@ownBard I'm calm. I simply explained why your justification is bullshit. Anyway, let the developer decide what is better for his app, I already gave my opinion.

**Comment by Adamantcheese** [comment]
I'll adjust the bounds of the text box for now, however it may change again in the future due to the following:

Moving the text editor tags into the main view is a decent idea, as they're more readily usable there, however they're also not used _that_ often. The only one of the bunch used often enough to warrant moving there would be the greentext one, which should probably be a context menu item like the "Quote" menu on posts. The rest of the text modifiers could also be context items, which is the best way to do it as it matches with the way the rest of the application works.

The captcha button and the submit button should really be one-in-the-same now; the error if you're posting too early would still be thrown, but after you solve the captcha, so it's queued up and ready to post as soon as the timer goes down to 0. This would also be in conjunction with #15, so that you can tell when you're able to post, so you don't hit submit too early and solve a captcha you didn't want to solve.

**Comment by Adamantcheese** [comment]
The text box size has been adjusted, however I'm leaving this open as the issue for the stuff I mentioned in the comment above.
