### ISSUE TITLE
[Suggestion] Don't open the sidebar menu when manually bookmarking threads

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#281]
Having the sidebar menu open makes sense when the thread watcher bookmarks a thread, but it's redundant for when you manually bookmark threads.

**Comment by Adamantcheese** [comment]
Should I make this an option rather than an always-on sort of thing? I'm already disabling the side drawer opening up if anything's filter watched while the application is in the background.

**Comment by Astridchan** [comment]
I guess it could just be disabled, I don't see why anyone would enable it if it was an option.

Then again, you remove it and someone will probably complain about it... It's your call.

**Comment by ownBard** [comment]
- If the thread is open then the bookmark button already gives you an indication that the thread is being bookmarked.
- If a thread is bookmarked in the background it's just obnoxious having the side panel suddenly open.

The only time it's reasonable to have the side panel open in my opinion is when the thread is manually bookmarked and there is otherwise no indication (e.g. using the bookmark option from the catalog).

**Comment by ownBard** [comment]
Or you could just make it a setting. Personally I'm fine with the way it is now.

**Comment by jdnixx** [comment]
I support this. Not a big deal either way. Don't care if there's a setting. It would seem kind of superfluous to have one

**Comment by floppyD** [comment]
I vote for making this optional. Sometimes I just bookmark a thread to follow it later and having the current sidebar behavior is convenient to jump straight to another bookmarked thread. I don't see having to tap to close the sidebar a big deal when I'm not going to use it. Maybe you can change the default behavior to be something like "thread is bookmarked -> show sidebar and wait for a tap for 0.5ms and then close it (and if there's a tap on the bookmark area, keep it open)" to make it more /aesthetic/?

**Comment by K1rakishou** [comment]
I think it should always open on the first (by first I mean after app reinstall/data clearing) pin/thread save click as a tutorial to show the user where the pins can be found. After that it can be optional. 

>If a thread is bookmarked in the background it's just obnoxious having the side panel suddenly open.

By the background pinning do you mean the new filter that automatically pins threads that match some regex? If so, then I guess instead of opening the sidebar after going foreground with new pinned threads we could show a snackbar with something like "N threads have been pinned" and a button that will open the sidebar menu. We could probably even highlight the newly pinned threads for a second or something like that.

>Maybe you can change the default behavior to be something like "thread is bookmarked -> show sidebar and wait for a tap for 0.5ms and then close it (and if there's a tap on the bookmark area, keep it open)" to make it more /aesthetic/?

Nah, I think it's too fast to even figure out whether you need it open or not and if we increase the delay then it will become a nuisance.

**Comment by ownBard** [comment]
One point, if you're making it a setting anyway having unique first time behaviour is redundant. In that case just have it on by default and once people get the hang of it they can choose to switch it off.

**Comment by ownBard** [comment]
Was I wrong?
