### ISSUE TITLE
[Feedback] Bookmark list indicators

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#283]
Not a big fan of the new bold / italics / underline indicators myself. Not sure if anyone else has an opinion on this.

**Comment by ownBard** [comment]
Despite that, I do think page limit should somehow be distinct from bump limit. Also I'm a little unsure of the need for an image limit indicator in the pins menu but I guess that depends which boards I use. There are plenty of other options, for example bubble indicators: 
![eZJhTMUZ](https://user-images.githubusercontent.com/51628221/62701748-983f4780-b9d4-11e9-8c3d-87637f1df3f4.png)
I'm sure something can be figured out.

**Comment by Adamantcheese** [comment]
The bubble indicator makes it look like there's something to be read, which is already covered by the post counter showing the number of unread posts, and it turns red if there's a reply. It would be misleading and confusing for the bubble indicator to show anything other than that.
As for the image limit, image dump boards like /c/ tend to hit image limit far before they hit bump or page limit, and threads are usually created right after they hit image limit to continue dumping.

I'll leave this open for any additional feedback on the bookmark info changes for the post counter displaying limits.

**Comment by Adamantcheese** [comment]
I'm going to use the question tag for feedback as well, why not.

**Comment by ownBard** [comment]
I would just suggest moving the post counter number into the bubble freeing up some space on the left that you could then use for icon indicators as well as stuff like the archived icon, closed thread icon etc.

**Comment by ownBard** [comment]
And then use the thread image on the right as the button for toggling thread watcher. Anyway I'm just saying there are other options.

**Comment by Astridchan** [comment]
In general, I think it's a good feature to have indicators for page limit and image limit, I'm sure it's something people will find useful. And since the bookmark info is already being used to display bump limit, it makes sense to use that to indicate page limit and image limit too. Ideal solution would be to display it like 4chan does, with separate number for reply count, image count and page number, which each getting italicised when they hit the limit (eg. 299 / 151 / _10_) but the space just isn't there so I think this is the next best thing.

I personally don't have much use for the page limit or image limit indicator though. The boards I frequent are active enough that a thread hitting the bump limit means it will get archived soon so a separate page limit indicator isn't necessary (compared to slower boards where it can take hours or even days before a thread at bump limit gets to page limit). In addition, the boards I visit aren't very image heavy so threads very rarely hit image limit. So for these reasons I'd like for the page limit and image limit indicators be made an optional feature, since I have to admit that if you have a lot of bookmarked threads having a mixture of italicised, bolded and underlined numbers on the bookmark list can make it look a little busy.

**Comment by Adamantcheese** [comment]
@ownBard Remember that there's a long/short bookmark info, one which shows the total posts in a thread while the other is new posts. Shoving the long string into a bubble isn't really possible, and with a large amount of posts, shoving just the new posts in might look kinda terrible since it'll be super small inside the bubble. You might want to make a mockup and see how it looks yourself.
Using the icon for the toggle is an alright idea, I'll keep it in mind.

@Astridchan Yeah, it would be a bit crowded there with the entire status cell text being in the watcher, which is why I went with this implementation. I can add toggles for the different limit statuses, but they'll be all on by default.

**Comment by ownBard** [comment]
Number bubble consistent with the one already used:
![mockup](https://user-images.githubusercontent.com/51628221/62748812-8e0b6080-ba49-11e9-8894-f6d24673ede5.png)
Moving the bubble to the bottom makes it look like a status instead of new messages:
![mockup](https://user-images.githubusercontent.com/51628221/62748883-cc088480-ba49-11e9-8769-9b1359df463a.png)
This one's just weird but I'll include it as a possibility:
![mockup](https://user-images.githubusercontent.com/51628221/62748867-beeb9580-ba49-11e9-93aa-19fbafb0afe2.png)
Not sure why no one's thought of this yet:
![mockup](https://user-images.githubusercontent.com/51628221/62748781-67e5c080-ba49-11e9-92d5-bcc19d3c44b8.png)

**Comment by ownBard** [comment]
@Adamantcheese Good point I hadn't thought of that.

**Comment by Adamantcheese** [comment]
That last one is actually really nice, but it might look a bit busy if you have a lot of bookmarks. Still don't really like the bubble indicator and the icon highlight is just weird and out of place. Could you mockup a full bookmark list with that last one?

**Comment by ownBard** [comment]
![mockup](https://user-images.githubusercontent.com/51628221/62750076-4f2bd980-ba4e-11e9-80f7-b1aaed34f9cf.png)

**Comment by Adamantcheese** [comment]
That's not bad at all. I can probably make the icons a little bigger if it's too cramped during implementation. Will definitely change to have it below the title, then I can probably do italics for everything individually just like the status cell in threads.

**Comment by Astridchan** [comment]
@ownBard You have the reply count, image count and page number there, but what about the unread post number? I guess it could just be in the same spot it is now, after the thread subject.

@Adamantcheese I remember you said earlier that having page numbers in the drawer would cause performance issues, is that still the case or have you found a way around that?
https://github.com/Adamantcheese/Kuroba/issues/40
>Page number italics: use last page notifications. I tried and it's way too laggy because of how many redraw events are called.

Also, looking at that red bubble indicator got me thinking that it could work to display the number of unread (You)s you have in each thread, is that something you'd consider useful?

**Comment by Adamantcheese** [comment]
I found a workaround for that, basically I just save a "last known" page number in the pin watcher from when a thread gets updated and every draw call pulls from that instead of actually requesting the page every single draw call.

**Comment by Adamantcheese** [comment]
I think that the red bubble notification would be good for that yeah. I'll think about it some more, along with #275 I have a lot of UI stuff to work on.

**Comment by ownBard** [comment]
@Astridchan Yes I do still have a lot of considerations but I'm trying not to be too overbearing with my opinion. I'm just trying to give rough ideas.

**Comment by Adamantcheese** [comment]
The more ideas the better, one of them will eventually stick around here.

**Comment by ownBard** [comment]
Alright well if you want more of my thoughts, I think with this change the thread watcher button might have to move after all, meaning the on/off indication should probably be something other than text colour.
- It's usually best to have any on/off indication on whatever the toggle button is (for thread icon you could possibly dim the icon or display a symbol in the bottom right, when toggled off)
- Using the thread icon as a button means you have to reach much further to the left of the screen which could be inconvenient when using one hand
- Using the thread icon as a toggle instead of opening the thread could become counter-intuitive putting a post number bubble on it
- As with what @Astridchan is saying there is plenty of space on the second line to put whatever information you would want (I just used the default small text that matches post numbers, filenames etc. but in practice it would probably look more like how the history tab is)
- If I recall the thread icons were made a little smaller so reverting to their larger size shouldn't be a big deal

**Comment by ownBard** [comment]
Kinda hoping someone will come up with a better idea for the thread watcher toggle that covers all these things.

**Comment by Astridchan** [comment]
Couldn't the unread post count just stay in the same position it is now, and keep that as the thread watch toggle? So basically putting all the ideas suggested here together we'd have something like this:

![62748781-67e5c080-ba49-11e9-92d5-bcc19d3c44b8](https://user-images.githubusercontent.com/40862101/62776314-e4f95000-bab2-11e9-8f39-ddc5b74bc296.png)

Red bubble indicator: number of (You)s in each thread
Below thread subject: total reply count / image count / page number
After thread subject: unread post count (*if* the bubble indicator for (You)s gets added then it's probably redundant to have the this go red)

**Comment by ownBard** [comment]
Looks too cluttered and it makes no sense for the (You) count to be so far from the unread post count. Not to mention it looks weird having them in two completely different styles.

**Comment by Astridchan** [comment]
Ok, what about without the (You) counter?

**Comment by ownBard** [comment]
Then it's better but separating the unread post counter from the other thread information is kinda redundant so you might as well just make it a textless button. An eye symbol for thread watcher or something silly like that?

**Comment by Astridchan** [comment]
I think the unread post count needs to be in a more prominent position than the rest of the thread information, because when I open the app/side drawer, the things I'm interested the most in seeing is 1. Do I have (You)s? 2. Are there unread posts? I think the unread post count is too inconspicuous if you just put it with the rest of the thread information.

**Comment by ownBard** [comment]
That's true. You could include the number bubbles but have them function the same as the one on the "hamburger" menu icon (i.e. number of unread posts but changes to red when you get a reply) and then just have a watch symbol button on the left. That would also make everything more consistent but I'm uncertain of the placements being right.

**Comment by ownBard** [comment]
It does feel a bit aimless to discuss this without the one making the decisions.

**Comment by K1rakishou** [comment]
Don't forget to find a good place for the thread downloading icon.

**Comment by Astridchan** [comment]
>It does feel a bit aimless to discuss this without the one making the decisions.

No harm in just throwing ideas around, as Adamant said the more ideas the better. Once he logs in he can give his opinion on the matter. He has the final decision anyway.

If we just kept the unread post count as is it would be something like this:

![unread](https://user-images.githubusercontent.com/40862101/62779692-98b30d80-babc-11e9-8bdf-2b856b6ba323.png)

I also made a mockup for if the unread count was a number bubble like it is on the hamburger menu and back arrow:

![unreadbubble](https://user-images.githubusercontent.com/40862101/62779787-d44dd780-babc-11e9-9d12-cc99fe25ae1d.png)

**Comment by ownBard** [comment]
https://files.catbox.moe/9w9wqs.png

**Comment by K1rakishou** [comment]
Damn, I personally really like the bubbles version but we need them to be clickable and as they are right now they are kinda small for that. Maybe instead of making them clickable we could just make the three dots menu at the end of the pin row? Then we could move the downloading icon to the bottom right corner of the pin image thus making a lot of space for the pin title. But with this solution you will have to make one more click to unwatch/watch the pin. We can't use long click for showing the menu here, because it is already used for pin reordering.

**Comment by Astridchan** [comment]
Just to clarify, you mean clickable to toggle the watcher? If that's the case, then maybe you could just make the whole thread thumbnail area toggle that (rather than just the bubble)?

**Comment by ownBard** [comment]
@K1rakishou Hey that's a fresh idea but yeah the issue isn't them being too small to click. Not sure if you saw my longer posts from earlier.

**Comment by K1rakishou** [comment]
@Astridchan 

>Just to clarify, you mean clickable to toggle the watcher?

Yes

>If that's the case, then maybe you could just make the whole thread thumbnail area toggle that (rather than just the bubble)?

Now that I think of it I think the button should be somewhere on the right side because it's easier to reach it. So I think the three dots menu is a possible solution for that.

>Hey that's a fresh idea but yeah the issue isn't them being too small to click. Not sure if you saw my longer posts from earlier.

Yeah I'm just saying that those things need consideration too.

**Comment by Astridchan** [comment]
How about just swapping the thumbnail from left to right? It'd make it easier to reach if the thumbnail was the toggle for thread watching.

![unreadbubble2](https://user-images.githubusercontent.com/40862101/62782935-f008ac00-bac3-11e9-8b5c-3d6999f716f2.png)

I don't really like the idea of having a separate icon *just* to be a toggle for the watcher, seems kind of redundant. 

If a three dot menu was implemented what other settings would it make sense to put there other than "watch/unwatch"? "Download thread" at least? "Archives" would make sense too.

**Comment by K1rakishou** [comment]
Yeah, stop/resume downloading would probably go there too. It's not implemented yet but one day it may be.

**Comment by ownBard** [comment]
@K1rakishou Hey man that's kinda rude to just ignore that I made these points already. Also worth noting that a three dot menu would make it much slower to toggle a larger number of threads and I don't know if the download toggle is really something that needs to be accessible from the sidebar.

**Comment by K1rakishou** [comment]
@ownBard 
Sorry didn't mean to be rude. I just kinda skipped through the thread only looking at the images. My bad, should've read the whole thing first.

**Comment by Adamantcheese** [comment]
Alright, so here's my weigh in:
1) Keep the thumbnail icon on the left, to match how the flow of the rest of the application goes (image -> text, never text -> image; the image is always the first thing to focus on). I've already made it toggle to be greyscale when the thread isn't being watched, for extra visual indication that you've stopped watching a thread. I'll add in toggle functionality for the icon being tapped for the time being; that way I can get some feedback on what feels better for toggling watch, tapping the amount of unread posts or tapping the thumbnail icon.

2) Putting the bubble icon above the thumbnail makes it look cluttered only when the icon is on the left. Because we're keeping the icon the left, the bubble indicator doesn't look great. The text on the righthand side will remain as-is and be the indicator for unread posts/replies, which ties into the next item.

3) The unread posts text for the long/short bookmark info will be changed as such:
   1) The long bookmark info setting will be removed, as the extra text will be underneath the title of the image.
   2) The info box will normally say "X" where X is the amount of unread posts, however if you have someone that responded to you, it will say "X/Y" where Y is the amount of replies you have.

4) The thread downloading icon will remain where it is right now, to the right of the unread text if applicable. This may change in the future.

5) A three dot menu is an interesting idea, but there aren't enough context options to really make it a necessary addition for every pin. Maybe in a future UI update that can happen, but not for now.

**Comment by ownBard** [comment]
Sounds good, I figured that would be your preference. Numbers on the left are fine, they could just serve to be a bit prettier in my opinion.
