### ISSUE TITLE
[Feature Request] Settings for screen rotation/orientation.

### ISSUE THREAD

**Issue by Qvess** [Adamantcheese/Kuroba#284]
Because of https://github.com/Adamantcheese/Kuroba/commit/dc13a4d68ddcb9b6d6d6a0389c01269a634dd571, the app currently follows the phones rotation sensor if android's auto-rotation is turned on and doesn't rotate at all if it's turned off.

Some Android roms (eg. LineageOS, CyanogenMod) allow setting specific rotation limits that are allowed for apps, but since the androidScreenOrientation is set to "fullUser" the app completely ignores this setting and just follows the rotation sensor.

Making a specific in-app setting to change the androidScreenOrientation would allow the user to change orientation behaviour to their liking.
Here's some personal suggestions for these orientation setting options:
Choose orientation (0°, 90°, 180°, 270°): Changes to "portrait", "reverseLandscape", "reversePortrait" and "Landscape" respectively.
Sensor rotation: "fullSensor"
System rotation: "user"
Rotating portrait: "sensorPortrait"
Rotating landscape: "sensorLandscape"

**Comment by Adamantcheese** [comment]
The current "fullUser" implementation already lets you do what you want, because it is a combination of fullSensor and user with respect to your system's rotation lock. The latter two are covered by fullSensor, and also by fullUser. [Per the documentation:](https://developer.android.com/guide/topics/manifest/activity-element#screen)
```If the user has locked sensor-based rotation, this behaves the same as user, otherwise it behaves the same as fullSensor and allows any of the 4 possible screen orientations.```
where user is
```The user's current preferred orientation.```
and fullSensor is
```The orientation is determined by the device orientation sensor for any of the 4 orientations. This is similar to "sensor" except this allows any of the 4 possible screen orientations, regardless of what the device will normally do (for example, some devices won't normally use reverse portrait or reverse landscape, but this enables those).```

Won't fix, you are able to work around this on your device already.

**Comment by Qvess** [comment]
I'm not quite sure if you understood what I actually meant with this.

What fullUser does is that it uses fullSensor if the rotation is enabled, however it doesn't check for the specific rotation modes.
Here's why this is a problem:
I have rotation enabled on my LineAge OS and have turned off the 180 degree rotation.
Other apps will respect this and won't use 180 degree orientation even if they support it.
However, since fullUser just detects that the rotation is on, it will use fullSensor and ignore the rotation modes set in Android settings.

**Comment by Adamantcheese** [comment]
Yes, turn off rotation and it will use the user setting. You will have complete control over the rotation.

**Comment by Qvess** [comment]
Let's be clear here:
**I want to use rotation, but don't want to use 180 degree orientation**
Turning off rotation through Android setting wont let me use rotation, you understand?

Now here's the thing:
LineAgeOS has two settings for rotation

**Auto-Rotation** (On/Off)
and
**Rotation Mode** (For disabling specific orientation 0,90,180,270 degrees)

Since the "fullUser" only cares about the Auto-Rotation being on/off it will set itself to fullSensor which doesn't care about Rotation Mode setting.
So, even if I disable 180 degree orientation from Android settings, the app will still use it.

And yes, I've tested other apps and they will only use the 180 degree orientation if I have enabled it from Android settings.

**Comment by Adamantcheese** [comment]
Ah, see I thought that when you said rotation mode you were specifying the rotation, not disabling specific rotations. So when you say you have 180 degree orientation turned on, which is to ignore 180 degree rotation ie reverse portrait, you want it to be like Clover, which uses whatever is default on your phone, which is exactly the reason this change was made in the first place, to allow the phone to rotate to reverse portrait.

If you can find an open source application that lets you do what you want, take a look in it's manifest file and tell me if it doesn't specify the screen orientation, because then you just want me to revert that change.

**Comment by Adamantcheese** [comment]
Also your use case is strange, what's the practical use for it? Shitposting in bed?

**Comment by Astridchan** [comment]
Excuse my ignorance, but would it be possible to leave screen orientation unspecified so it uses the system settings, and then add a setting to Kuroba for "Use full/180 rotation" that sets it to fullUser?

**Comment by Adamantcheese** [comment]
Yeah, but if it's literally one person with one complaint then it's not enough of an issue to warrant putting in an entire rotation suite of settings into the application. A practical reason for the change will convince me more than anything else.

**Comment by Astridchan** [comment]
>Shitposting in bed?

Not that guy, but my previous Android phone didn't allow you to lock it to landscape, only auto-rotate or locked to portrait. Many Android phones have it like this, I guess it's because some apps aren't compatible with landscape? Anyway, If I was shitposting in bed I liked to hold the phone in landscape while laying on my side. Now if you're laying on your right side it's an issue to have the auto-rotate on because the phone will be held upright and switch to portrait. But if you lay on your left side the phone is upside down, and since almost no apps rotate 180 degrees it's fine and the phone stays in landscape. Or it would have been fine if one of the apps I used wasn't set to rotate to reverse portrait so it always became a huge hassle when switching between apps when everything else stayed in landscape and then there is this one damn app that insists on rotating to reverse portrait, making me either change my position or lock the phone to portrait every time I used that app.

Not an issue on my current phone though, which doesn't seem to rotate 180 even with the https://github.com/Adamantcheese/Kuroba/commit/dc13a4d68ddcb9b6d6d6a0389c01269a634dd571 commit, I'm guessing the manufacturer's Android version just completely ignores the `android:screenOrientation="fullUser` part.

**Comment by Adamantcheese** [comment]
Okay, so when you're in bed, you're holding your phone in landscape, with reference to your eyes, as if you were watching a video or something. The actual orientation the phone understands is portrait from this perspective. If you flip over, then the whole phone flips upside down, which would, from the phone's perspective, make it reverse portrait. And that would make the whole thing flip upside down to correct for the new orientation and display everything correctly with respect to gravity, but I guess @Qvess doesn't like or want to adjust to that new viewing angle and prefers reading things in that particular direction? If it really boils down to just personal preference then I'm not going to change it and would instead say to just remove that line from the manifest and build it yourself.

**Comment by Qvess** [comment]
Bed shitposting was the exact reason for this request.
I think that a possible way to handle this would be to leave the `android:screenOrientation` unspecified and when starting the app use `activity.setRequestedOrientation()` to set the orientation to a specific mode. Don't know how easy this would be to implement though, I'll try to look for other options.

**Comment by Adamantcheese** [comment]
Alright, now that I know what people actually want, I can slap in a setting and do that.

**Comment by Astridchan** [comment]
@Adamantcheese 
Yeah, so I'm holding phone in landscape with reference to my eyes. I can't lay to my right because phone is now in portrait, but I can lay to my left side because 99% of apps won't rotate to reverse portrait. Except for that one app that does and now the app is in reverse portrait while I'm holding the phone in landscape.

My two 2c is to make it **not** rotate 180 by default simply because that's how pretty much all other apps work in my experience, and then make 180 rotation optional. Not a big deal for me either way personally, since like I said my current phone simply won't rotate 180 no matter what the orientation is set to in the manifest.

**Comment by Adamantcheese** [comment]
Yeah, I'll change it to be a setting with fullUser on by default.
