### ISSUE TITLE
[UI/UX] Use LRU behavior for pins list

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#287]
What do you think of implementing LRU (Least Recently Used) behavior for pins list? 
When a pin gets updated and there are new posts this pin will be brought up to the top of the list. The pin that was previously at the top will be shifted one position down. This means that active threads will always be closer to the top of the list and not active/archived will be closer to the bottom. This will probably break pins reordering so we will have to disable it when this behavior is active. I think this should be more convenient than manually moving active pins to the top and archived to the bottom. (I mean every thread on every board works like this)
What do you think?

**Comment by ownBard** [comment]
Is there any downside if it can be switched off? I like to sort my pins manually so I always know where they are.

**Comment by Astridchan** [comment]
This would conflict with how I've got into a habit of grouping my pin list. Basically I put the generals I follow first, then the non-general posts I've bookmarked, then archived threads:
/abc/- abc general
/zyx/ - zyx general
/123/ - 123 general
random thread 1
random thread 2
random thread 3
archived thread 1
archived thread 2
archived thread 3

That way if I want to open /abc/ general I always know where to find it on the bookmark list. If the feature you suggest was added then every time the pin list updates (every 15 seconds is it?) the threads move position based on activity so you'd always have to look through the list to find a specific thread.

Also, updating the pin list ordering should only happen in the background when the drawer is closed. When the drawer is open the order should remain static, otherwise you might try to open a thread just before the pin list updates and the thread you're trying to open moves into another position in the list.

If you can make it optional, then sure, go ahead, but I personally wouldn't probably use it.

**Comment by K1rakishou** [comment]
Yeah, this is probably not a good idea.
