### ISSUE TITLE
thread archiving doesn't download media when preload is off

### ISSUE THREAD

**Issue by nahdoubtit** [Adamantcheese/Kuroba#288]
If you have "automatically load images/videos" set to never, thread archiving will not download any media. It will only create the folders (board name, thread id, media folder) and thread.json. Changing to WiFi (and being on wifi 😏 fixes it.) No clue about being on 4g and having it set to always, but assume that works if wifi only works. Media prefetching was disabled both times. I had posted in kuroba general asking about it, and after a response tested it myself.

**Comment by K1rakishou** [comment]
The current logic is such that if you have no WiFi connection no images will be downloaded. It's implemented this way to save the traffic because it may cost money (This is actually the default behavior for showing any images/files in Clover/Kuroba). Try turning WiFi on and then download a thread again. It should work. Media prefetching should not have anything to do with it.

**Comment by nahdoubtit** [comment]
I should have worded it better. If automatically load images/videos is set to never but you are on wifi connection it still won't work. But it does work fine if that setting is set to WiFi/always and on wifi connection. If this is the intended way it works, like you said, to save data, and will only archive media IF autoload image/video is set to WiFi/always then you can close the issue. I just assumed with auto load images/videos still set to never, but on wifi, itd still download in archive mode, just like just because that's set to never, you can still click on a photo/video, view it, and manually download it. I just have automatically load images/videos set to never because majority of time I don't want to see them, and don't want to load something I'm not going to view (and I do have data limits even for wifi home connection), for a majority of boards I'm in, but obviously if archiving I do want media saved. Seems like it's just a user end error for how I have my settings and want it to work, but is limited to me. So you can close this.

**Comment by K1rakishou** [comment]
>If automatically load images/videos is set to never but you are on wifi connection it still won't work.

This is how it's supposed to work since I'm using this setting to figure out whether I can download images or not. So if you disable images downloading even with WiFi turned on then images won't be downloaded.

> I just assumed with that still set to never, it'd still download in archive mode

No it shouldn't. That setting is global (well with some exceptions) for the whole app.

I think that maybe there should be a dialog that allows you to override this behavior when clicking download thread button. Maybe one day it will be implemented.

**Comment by nahdoubtit** [comment]
> > If automatically load images/videos is set to never but you are on wifi connection it still won't work.
> 
> This is how it's supposed to work since I'm using this setting to figure out whether I can download images or not. So if you disable images downloading even with WiFi turned on then images won't be downloaded.
> 
> > I just assumed with that still set to never, it'd still download in archive mode
> 
> No it shouldn't. That setting is global (well with some exceptions) for the whole app.
> 
> I think that maybe there should be a dialog that allows you to override this behavior when clicking download thread button. Maybe one day it will be implemented.

Just knowing that it works by the setting is enough, at least I know why it didn't work and how to archive. If you'd like to make an archive override behavior for that setting, it'd be cool, but obviously isn't a critical thing. Thanks for explaining it to me, and thanks for the hard work. So you can close this since it really isn't a bug, or leave open if you want for that "maybe implemented one day.
