### ISSUE TITLE
[Suggestion] Easy close empty searchbar

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#302]
If the searchbar is empty it should close when unfocused or if the keyboard closes since there's no need to keep it open.

**Comment by Adamantcheese** [comment]
The keyboard never becomes unfocused due to the layout structure, and detecting whether or not a keyboard is open is apparently way too difficult for some stupid reason. Adding that this is a very small item that doesn't affect much (despite this being a good QOL update), I'm going to close this and mark it as wontfix.
