### ISSUE TITLE
App breaks opening image from search

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#320]
It happens very inconsistently. Here's the bug in action: **https://files.catbox.moe/8rwlgf.mp4**

**Comment by Adamantcheese** [comment]
Yeah this happened to me once as well, only an app restart fixes it. I think it's a double tap thing but I have no idea. I'm going to mark this as cantrepro for now because I don't have a good set of steps to debug with.

**Comment by K1rakishou** [comment]
It looks like it opens the image controller but for some reason the image view itself does not show up. Is the immersive mode enabled? By the way, how do we handle motion events in that controller. I mean what view do we use to get the touch events from? If it's the image's view then it's pretty obvious why it doesn't respond (there is no view to get events from).

**Comment by K1rakishou** [comment]
Huh, for me this bug is 100% reprodicible in both board/catalogs modes. Without immersive mode. You have to enter some text into the search bar so that the threads list updates itself (the amount of threads should become fewer than before search). After doing so, opening any image in that state breaks the app.

**Comment by ownBard** [comment]
Without immersive mode. Each image either consistently has the bug or consistently doesn't, but I can't figure out why.
