### ISSUE TITLE
[ENHANCEMENT] Dynamically generate splash screen with theme colours.

### ISSUE THREAD

**Issue by sharppaul** [Adamantcheese/Kuroba#322]
Currently it's very... White. I know it's a temporary splash screen to test some things, but it would be nicer to have it themed the right way.

**Comment by Adamantcheese** [comment]
Unfortunately due to the research I did yesterday, I can't have the splash screen themed to your selected theme like how I wanted it to be. The theme specified in the manifest takes priority over everything else when loading the application, and so I can't change it. I've modified the splash to be black and just have the logo however, which you can see here https://github.com/Adamantcheese/Kuroba/commit/53c2bcf4d651b8678e79c55c476c4223987f8bc4

**Comment by Astridchan** [comment]
@Adamantcheese 

Can the splash screen be switched between light/white and dark/black depending on whether a light or dark theme is set in the app? Or is this stuff Android Q only?
https://developer.android.com/preview/features/darktheme#launch_screens

**Comment by Adamantcheese** [comment]
Nope, Android Q only. I'm really surprised this is coming out literally just now.
