### ISSUE TITLE
[BUG] Weird glitches when swiping bookmarks away with 404 threads in bookmark list

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#336]
![ezgif-2-81aabfc639c6](https://user-images.githubusercontent.com/40862101/63695463-6bd35a00-c821-11e9-9a45-7dbead1bd062.gif)

**Comment by Adamantcheese** [comment]
The adapter is updating for a brief moment due to the removed item; everything after the removed item is being updated. This is because I have view recycling turned off for the drawer, due to the text styling previously not being removed from the view when it was recycled, and this was my only solution. Won't fix, because I have no other fix.
