### ISSUE TITLE
Threads getting "unbookmarked"

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#341]
![ScreenRecord-2019-08-26-20-04-49](https://user-images.githubusercontent.com/29208110/63776419-c28b7300-c8b7-11e9-9fb9-d76ecc2be85a.gif)

**Comment by floppyD** [comment]
To be clear, they don't really get unbookmarked, it's just the icon being buggy.

**Comment by Adamantcheese** [comment]
Does this still occur with thread downloading turned off?

**Comment by floppyD** [comment]
No, disabling it fixes the issue.

**Comment by Adamantcheese** [comment]
It's another issue with thread saving doing something with the loadables then, so it's in K1rak's domain as he knows that side of the code more than I do.

**Comment by K1rakishou** [comment]
Uhhh, I think it's either because of this method 

https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/ViewThreadController.java#L537

or this one

https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/controller/ViewThreadController.java#L501

I had the same problem when I was testing SAF (I thought that I introduced the bug but then I found out that it exists in the release too) with the download thread icon, where the animation wouldn't start, exactly because of one of those methods. If you comment the whole populateLocalOrLiveVersionMenu() method out then everything works (and there is the incrementalThreadDownloadingEnabled check, btw). I tried to fix it but it would still reproduce sometimes. Making the setSaveIconState(true) to be called after the populateLocalOrLiveVersionMenu() doesn't fix it either.
I guess it's because the toolbar gets recreated and everything resets so we need to find another way for this.
