### ISSUE TITLE
2ch.hk changes to Sushichan after restaring the app

### ISSUE THREAD

**Issue by hearme1** [Adamantcheese/Kuroba#351]

**Comment by K1rakishou** [comment]
Yeah, apparently it's because we have removed some sites (8chan and 55chan I guess?) so the ids probably mix up with each other. I think instead of completely removing them it's better to use some kind of stub (empty site) otherwise it won't work. This is the problem with the database I was talking about when suggested rewriting it.

**Comment by Adamantcheese** [comment]
It's because 8chan was removed that everything got shifted down by one (per the site registry). It should only happen once anyways.

**Comment by K1rakishou** [comment]
It actually happens on every app restart.

**Comment by Adamantcheese** [comment]
Weird. I'll take care of this because it's something I did that caused it.

**Comment by K1rakishou** [comment]
Just use a site stub instead of deleting it completely.
