### ISSUE TITLE
Poster ID features

### ISSUE THREAD

**Issue by aqua-lzma** [Adamantcheese/Kuroba#353]
Highlight posts by id
Also show how many made by that id
Would make it easier to detect shills, you know?

**Comment by Adamantcheese** [comment]
Highlighting posts by ID is already covered by filters.
Would how many cover board global or thread local, because if it's global I'm not doing that.

**Comment by ownBard** [comment]
It would only make sense for thread local since most sites use randomized IDs for each thread, right?

**Comment by Adamantcheese** [comment]
I have no idea how IDs work which is why I was asking.

**Comment by ownBard** [comment]
Ah okay, well they are random and different each thread (use to identify posts made by the same IP). I imagine most people on ID boards find using global filters counter-intuitive because of this so I assume he's just asking for in-thread features for navigating posts by their IDs, showing number of posts with the same ID etc.

**Comment by ownBard** [comment]
Also LOL I just realised who this user is.

**Comment by Adamantcheese** [comment]
This adds the count to the post info box. Highlighting by ID was already a menu option that I didn't know about, and both of those are thread local.
