### ISSUE TITLE
image editing/re-encoding broke

### ISSUE THREAD

**Issue by nahdoubtit** [Adamantcheese/Kuroba#370]
depending on the combination of options selected, you get this error: 
![1569929599198](https://user-images.githubusercontent.com/49420169/65978137-ac4a7700-e462-11e9-97e1-c0cf06a3c972.jpg) (stole pic from an anon in a /g/ thread, thanks  anon!) When trying to apply image editing options. You can do each option individually without error, but doing "remove filename" and "remove metadata" you get that error. "Change image checksum" and "remove metadata" is fine, etc. Any multiple option along with remove file name won't work. I'm assuming #356 fix caused this issue.

**Comment by Adamantcheese** [comment]
Yeah I've already pushed a fix for that in https://github.com/Adamantcheese/Kuroba/commit/bb87d2796e7addfc593ceaab0bd8091f1dbb0211. You can temporarily work around this issue by long-pressing the image name in the expanded reply box, assuming it has an extension on it (otherwise it'll probably crash as well and I'm going to fix that).

**Comment by nahdoubtit** [comment]
Sorry didn't see you had fixed it already. Thanks for the response. And neat, never knew you could do that, long press on name in extended reply box. Thanks cheese!

**Comment by Adamantcheese** [comment]
It's fine, I'll probably push out a fix in a little bit because I know it's pretty annoying of a workaround.
