### ISSUE TITLE
watcher(?) wakelock while not watching any threads

### ISSUE THREAD

**Issue by 1sad** [Adamantcheese/Kuroba#373]
![Screenshot_2019-10-06-15-37-16](https://user-images.githubusercontent.com/23120024/66269324-d1b6f680-e84f-11e9-9625-835aa5531efe.png)

goes away with watcher COMPLETELY disabled in the settings

**Comment by Adamantcheese** [comment]
If you've got the watcher on and aren't watching anything, the wakelock will still be triggered, yes. It's immediately released though because there's nothing to update. Not going to change it, no real performance impact (not that I know what you want me to change?)

**Comment by 1sad** [comment]
its an unnecessary wakelock that does nothing but drain your battery
why does it have to be on when nothing is getting watched? why is it working normally in clover? why did you remove the watcher notification light setting too, while were at it

**Comment by Adamantcheese** [comment]
I looked at it some more; the wakelock is never utilized if there are no pins; the wake update receiver will get the background message (which is what you see), but nothing else will occur other than checking if threads need updating; if there are threads, a wakelock is acquired at that time so that network activity won't be restricted. If you have filter watching enabled then a wakelock will always be acquired as it loads catalogs not threads. Again, no real performance impact; if you want to have a better battery life, change your background update time from 5 minutes to something greater. AFAIK Clover moved away from this method recently which is why you likely don't see it if you're running the dev version.

Notification lights are now on a per-channel basis in later Android versions, which made it difficult to support both implementations. I made it static to make it easy on the development side; you can use an external app to change the notification color or upgrade your Android ROM to 8.0+.

Also not calling me incompetent will be a boon to me actually responding to your question, as well as actually providing info in your issue, because I didn't know what you wanted me to fix. And there's nothing to fix anyways.

**Comment by 1sad** [comment]
sorry, had a real bad day.

the point im trying to make that even if i click "stop watching" in the notification the wakelock is still there, and drains battery without actually doing anything, and for it to stop you have to manually go into the settings and disable the watcher completely to remove the wakelock.
it would be nice to have it stop waking the device when there is absolutely no reason it should, as there are no threads with watcher enabled.
it just removes a tedious manual step you have to do when you want your phone with 95% battery in the morning instead of 85% for me. even if battery drain is not that much it still triggers my optimization autism.

either way, sorry for being a dick and thanks for updating the app.

**Comment by Adamantcheese** [comment]
The wake update receiver and the wakelock are separate functions; the receiver is always called because the watcher is on, however the wakelock isn't acquired unless it is necessary to update a thread; you can take a look at that code here:
https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/WatchManager.java#L918-L920
In fact, the same code is still in Clover and hasn't been touched other than moving the lock method to another class:
https://github.com/chandevel/Clover/blob/9efd5d6803350c0c5b82e35fc5d1f6676974bc23/Clover/app/src/main/java/org/floens/chan/core/manager/WatchManager.java#L621-L623

The code that actually registers the wake update intent is essentially the same as well, just refactored to a different class so the single wake could be used for more than one action (filter watching mainly). You can compare the code for the two here:
https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/manager/WatchManager.java#L762-L794
https://github.com/chandevel/Clover/blob/9efd5d6803350c0c5b82e35fc5d1f6676974bc23/Clover/app/src/main/java/org/floens/chan/core/manager/WatchManager.java#L510-L541

As a note, the AlarmManager is already fairly optimized by the Android team themselves: "Note: Beginning with API 19 (Build.VERSION_CODES.KITKAT) alarm delivery is inexact: the OS will shift alarms in order to minimize wakeups and battery use." https://developer.android.com/reference/android/app/AlarmManager.html

If you're worried about the application draining your battery, once again I recommend lowering the background update time to be the default (15 minutes) or longer. My battery doesn't drain more than 3% overnight and I've had my phone on for months without a restart. It's possible that your battery may be going bad with that level of battery drain, or something else is draining your battery. Really it should be your last suspect for optimization. If you can more concretely prove that it is Kuroba that is causing the battery drain then I'll take a closer look at what I can do, because right now nothing has really changed from Clover.
