### ISSUE TITLE
[Feature Request] Change theme on Sunset/Sunrise

### ISSUE THREAD

**Issue by rdrms** [Adamantcheese/Kuroba#374]
My Xiaomi does this with the launcher and it's pretty slick.  Twitter also does it, it requires a location permission. Basically I love Photon during the day as it's nice to read, but at night I prefer Black, but ideally the two themes would be customizable. Thanks for considering my request.

Main hurdles would be the implementation and scaring people off if the location request wasn't tied directly to the sunset theme setting.

**Comment by Adamantcheese** [comment]
Because of the way that themes work in the application, the whole application needs to be restarted when that time is hit, which would be really weird if it just happened without a prompt (and those other applications probably do it without a prompt). If you do want this feature that I believe would basically only be for you, I recommend developing it yourself. I'll leave this open for now if anyone wants this feature as well however.

Another idea would be to redo the theme picker to make it quicker to pick a theme, if that would help.

**Comment by Adamantcheese** [comment]
As it seems nobody else wants this feature, I'm going to close this. Too much development effort for one person.
