### ISSUE TITLE
[Bug] Opening archive of 404d thread from history opens the last opened thread from catalog instead

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#385]
Demonstration: https://gfycat.com/scientificsoggycod

This only happens when using the button, not when going into the 3 dot menu and selecting archives from there.

**Comment by Adamantcheese** [comment]
From my testing, if this was specific to Nyaafu, it doesn't seem to happen anymore. The specific ways that URLs are mapped per archive isn't specified in mayhemydg's archives.json file, so that may be the cause. Regardless, the "correct" URL `https://archive.nyafuu.org/vp/thread/41186754/#41186754` and the one I'm generating for the loadable `https://archive.nyafuu.org/vp/thread/41186754#p41186754` both lead to the same page now.
