### ISSUE TITLE
[Feature Request] New duplicate file saving

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#39]
Can't you put like a 5 seconds countdown when saving a file (if the filename is the same, so if you press the download button twice it doesn't save two copies of the same file) and some hash checking if you try to save another file with the same filename after the first 5 seconds? And if the hash doesn't match, you can offer us to either rename the file or just add a "(1)" or something like that if possible.

**Comment by Adamantcheese** [comment]
You get a random string of garbage at the end of the filename if you save a duplicate. Don't fat finger the button and save duplicates. Also I would have to download the file if I was to do that suggestion, which is why I removed the duplicate checking in the first place, so you wouldn't download the file in the first place. This isn't a ~~shitpost image~~ media organization app, it's a browsing app.
