### ISSUE TITLE
[BUG] When downloading the whole thread's image gallery, create sub directories settings are not applied

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#394]
![image](https://user-images.githubusercontent.com/10332458/67622597-54661c80-f824-11e9-96fb-1e2f4d8108e4.png)

![image](https://user-images.githubusercontent.com/10332458/67622666-0867a780-f825-11e9-9e6e-8b2266d6cc1e.png)

If you look at the code saveBoardFolder and saveThreadFolder settings are only being used in ImageViewerController.
But when downloading them manually they are applied as they should. Also bad characters are not being filtered out (like spaces).

**Please, for the love of god, lets do this task after the SAF is merged (it's almost done) because otherwise there will be a lot of conflicts for me to resolve.**

**Comment by Adamantcheese** [comment]
Kinda inconvenient I know, but I closed https://github.com/Adamantcheese/Kuroba/issues/377 yesterday which did touch ImageSaver. Really all it did was allow you to save the original filenames when downloading albums, just like how you can for single images, and added a bit of text in the settings to say that those two settings don't apply to albums. I don't think there should be that many conflicts with that change, if any. I'll leave this open because it's not a dupe, it's actually a separate issue.

**Comment by K1rakishou** [comment]
So, are we going to implement this one? I think it should have the same behavior as when you download images separately and those two settings are turned on. But maybe there is some other meaning to how it works right now and I just don't know that.
