### ISSUE TITLE
Inlined pdf files cannot be viewed

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#422]
Thread - https://boards.4channel.org/g/thread/73640314
Link to the file - http://chinkshit.xyz/infographic.pdf

Maybe we shouldn't even inline pdfs?

![image](https://user-images.githubusercontent.com/10332458/69223476-7a18e400-0b8c-11ea-9562-1bd0abddce5b.png)

**Comment by Adamantcheese** [comment]
Yeah I double checked the behavior for PDFs on /tg/ and it's basically the same, with a different thumbnail. It does provide a convenient way of downloading the PDF however, so I don't see it as a bug. I do think that adding the file extension to the "Spoilered image" toolbar text might be helpful though, because right now you wouldn't know this file was a PDF.

**Comment by ownBard** [comment]
The error message should probably be changed to something like "filetype not supported" in these cases instead of the standard "failed to show image." Maybe even hint that downloading is still available.

**Comment by Adamantcheese** [comment]
Put that in.
