### ISSUE TITLE
Broken webm thumbnails on arisuchan

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#435]
Posts with webms fail to display thumbnails making them untappable, though swiping through image viewer will display the webm as normal.

**Comment by Adamantcheese** [comment]
It seems that, for whatever reason, WebMs specifically have JPG instead of PNG thumbnails like everything else. Given that Arisuchan is running on Vichan, I would honestly say that this is an error on Arisuchan's end, because every other Vichan site uses PNG thumbnails for all files.

While I can put a mitigation in, chances are that Arisuchan's mucking with Vichan internals caused other imageboard viewers to cause webms not to load thumbnails either. I'm going to tell you to go ask them to fix it for that reason.
