### ISSUE TITLE
Copying a greentext and pasting it in the post box keeps the text green

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#441]
Pic related
![Screenshot_20191130-103506_Kuroba](https://user-images.githubusercontent.com/29208110/69901192-65430a00-135d-11ea-90e0-3ef6a9893bf4.png)

**Comment by ownBard** [comment]
Also occurs with other formats such as copying headers from webpages etc. It has no functional effect though.
![HgxJXmHx](https://user-images.githubusercontent.com/51628221/69907505-0cf82080-13ce-11ea-9973-1749f25c633d.png)

**Comment by Astridchan** [comment]
This issue is somewhat related to this one: https://github.com/chandevel/Clover/issues/679
I've seen a couple other people report that same bug on 4chan so it's not something that's completely unique to my devices.

Would it make sense to automatically turn any text pasted into the post box into plaintext? That would fix both issues I think. Do any of the supported *chan sites support formatted text in posts?
