### ISSUE TITLE
[IMPROVEMENT] Show progress description when loading a thread/board

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#461]
Like: 
- "Parsing HTML"
- "Extracting posts" 
- "Parsing YouTube links' titles"
- "Parsing inlined files" etc. 

So the user can see what takes the loading time. It should be displayed on the view where the progress bar is shown.

Why? Because some settings may slow down the loading speed and it's not obvious why, so people start complaining.

**Comment by Adamantcheese** [comment]
Because all the post parsing is multithreaded, this isn't exactly possible. There are distinct stages for every post, but not for the whole thread.

**Comment by K1rakishou** [comment]
Hmm, then maybe we could add some kind of statistics where we sum up all steps for every post, separate them into groups and then the user could see it somewhere in developer settings or something like that? Something like:

"Parsing HTML took 1000ms"
"Extracting posts took 500ms"
"Parsing YouTube links' titles took 3000ms"
"Parsing inlined files took 500ms" etc.

 We should also probably add hints that some settings may increase the thread/board loading times.

**Comment by Adamantcheese** [comment]
The only thing that would currently cause issues with loading as it does extra requests is Youtube title parsing. Everything else takes very little time to process in comparison, threads with over 500 posts in them take less than 2 seconds to process. If you're having issues loading anything, I'm going to point to your network being slow rather than the application.

**Comment by K1rakishou** [comment]
>The only thing that would currently cause issues with loading as it does extra requests is Youtube title parsing

Well I'm actually talking about them.
