### ISSUE TITLE
Webm linking and errored thumbnails cause weird behavior for image viewer.

### ISSUE THREAD

**Issue by Coy-Allen** [Adamantcheese/Kuroba#462]
I first noticed this problem on 4.10.1 but it persists even after updating to 4.10.2 and deleting the database.

The problem is that when I looked at a webm on /pol/ that was added with "image link loading" that was linked to a webm from /wsg/.

![Screenshot_20191218-182505](https://user-images.githubusercontent.com/22683505/71133345-400d2300-21c8-11ea-8788-1e208214a49f.png)

Post from /pol/:
https://boards.4chan.org/pol/thread/236591861#p236602317
Original post from /wsg/ that had the webm:
https://boards.4channel.org/wsg/thread/3190576#p3201496
The link was loaded twice but that isn't the big issue. I clicked on the image of the bondage cat dude then swiped to the errored webm, enabled sound, swiped to the repeat image and then swiped again, then closed the image viewer. The viewer then showed the thumbnail of the bondage cat dude for 3 seconds then closed like normal. The problem was that the sound from both webm files was still playing. This continued even when I closed the app and only stopped when I rebooted the phone.

This problem does not happen when viewing webm from the /wsg/ thread, only the /pol/ thread that links to it.
I should also note that the image viewer lagging when closed has happened before but I couldn't find a pattern as to why or how and I could never replicate it. I think it occurs if the image is missing its thumbnail but I can't say for sure.

So I think that the bug is that the image viewer has problems with webm files that have no thumbnails.

**Comment by Adamantcheese** [comment]
It's not that they didn't have thumbnails, it's that I was setting the thumbnail to be the webm file itself. Because a linked file may or may not be from the same site as the board you're browsing, I don't currently have any special code to get a thumbnail for it and was just using the file itself as the thumbnail, which is definitely wrong for anything that isn't a static image (thus it showing Error). So that's fixed now and should fix the rest of those problems as a result. Also I've added some synchronization so you shouldn't get double-linked files.
