### ISSUE TITLE
[IMPROVEMENT] Make the JS captcha fill the whole screen

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#467]
I dunno if it's just my phone, but I have to scroll horizontally in order to fill it.
![ScreenRecord-2019-12-20-14-03-04](https://user-images.githubusercontent.com/29208110/71272323-533c0200-2332-11ea-9cbb-927922e91274.gif)

**Comment by Astridchan** [comment]
The issue seems to be related to the DPI / display size setting, I use "small" and it makes the Captcha go outside of the screen like in your image, but if I set the display size to "default" or "large" the Captcha fits to the screen:

![Screenshot_20191220-193137 (1)](https://user-images.githubusercontent.com/40862101/71278538-8c8b6680-2360-11ea-8fb5-4c730418e49e.jpg)

**Comment by Adamantcheese** [comment]
This is the best I could do, and there's nothing else I CAN do. See the following: https://stackoverflow.com/a/39314870
