### ISSUE TITLE
8chan crash issue.

### ISSUE THREAD

**Issue by TehSViN24** [Adamantcheese/Kuroba#47]
Add 8ch.net
Proceed to add board on 8ch.net.
Application will soon freeze.
High possibility back,home buttons do not work.
Stop application.
Next time you open the application you get a white screen.
Only gets fixed by deleting all application data.

**Comment by Adamantcheese** [comment]
This is probably because right now when you add a board on 8ch, even though you have only one SAVED board, the database saves ALL boards, which means every single board that was parsed from boards.json is saved to the internal DB. Really stupid imo, probably gonna change that because either way boards.json should be parsed every time you open up that page, which is infrequently.

That being said, it's trying to load over 18k boards. That's why it's freezing.

**Comment by TehSViN24** [comment]
Oh that makes sense since the application cache was at 20mb after doing that

**Comment by Adamantcheese** [comment]
For the time being I'll revert it to be the old style where the boards aren't listed and you need to input the usual board code to add a board. My comment above still stands though for the future.

**Comment by Adamantcheese** [comment]
Because 8chan no longer functions, I'm going to be closing this issue. I may be removing 8chan in the future because of it's non-functionality on the clear net and I don't want to add in extra functionality for TOR-only websites.
The underlying issue here still remains, however with the relatively small number of sites and boards currently supported it isn't pressing enough to warrant the changes needed to fix this.
