### ISSUE TITLE
[Feature Request] RAM Cache

### ISSUE THREAD

**Issue by OXiDE-dev** [Adamantcheese/Kuroba#49]
Add a setting to store the cache in ram instead of storing it on the disk. 
I don't want every picture I scroll by on 4chan on my disk.

**Comment by K1rakishou** [comment]
It's not a good idea to store images in the memory (maybe only previews). They take a shit ton of memory and you will probably have like 5-10 images in the cache at a time. And what if an image has dimensions like 9999x9999 (that's like 300MB)? You won't be able to allocate this much memory and the app will crash immediately. And if you think that your phone has enough memory then, unfortunatelly, you are probably wrong since Android applications are not allowed to use ALL of the phone memory, just some fraction (depends on device) after that OOM will follow (and even if your device can do that, there is the memory fragmentation). And, by the way, IIRC Clover/Kuroba do not save the originals of images when you scroll a thread, just their previews, but I may be wrong here (and if I'm then it is probably a bug).

 It's probably a better idea to add an option to disable disk cache. But then you will be redownloading images in the same thread every time you open it.

**Comment by Adamantcheese** [comment]
K1rak explained it quite well.
