### ISSUE TITLE
Reply alert won't get removed until you unfollow all threads [video]

### ISSUE THREAD

**Issue by Esildor** [Adamantcheese/Kuroba#509]
You have to stop tracking all threads to remove a notification. Also going to the thread and viewing all replies doesn't remove the notification either.

Video:
https://imgur.com/a/asCG9tb

Pixel 4 up to date

**Comment by Astridchan** [comment]
Have you changed Kuroba notification settings? If you disable the watch notification (as in the pic below) it will cause (You) notifications to become unremovable.

![Screenshot_20200109-223305](https://user-images.githubusercontent.com/40862101/72252734-92dfcc00-3608-11ea-9e97-3f341ac47c9f.jpg)

**Comment by Esildor** [comment]
Ah, I do. So that would explain it.

However, this feels like a strange behavior. Is this a bug? And if not, humor me and explain how this is desirable?

**Comment by K1rakishou** [comment]
Because Google forces everyone to do it: https://developer.android.com/about/versions/oreo/background#services

Either this or the service will be killed by the OS after couple of minutes of execution when the app is in background which means the (You)s won't be updated as frequently as they are updated right now.

**Comment by Astridchan** [comment]
The issue here isn't with the watcher notification itself, it is possible to disable it in the notification settings (see screenshot above) and still receive reply notifications. What is an issue is that reply notifications don't get cleared anymore by scrolling to the bottom of the thread you're replied in like they're supposed to if you have watcher notification disabled.

**Comment by K1rakishou** [comment]
@Astridchan 
So you need to disable the (You) notification in the settings (the icon), get a (You) and then scroll to the bottom and this won't clear the notification right? What about the red number in the pin drawer? Will it become normal or will it stay red? Seems like a bug.

**Comment by Astridchan** [comment]
You need to disable the "watch notification" channel which is for the "you are watching X threads" notification, and keep "watch alert notification" for (You) notifications enabled.

The red number on the drawer hamburger button and in the bookmark list does go back to normal, only the notification itself fails to go away.

**Comment by K1rakishou** [comment]
@Astridchan Alright, thanks.

**Comment by K1rakishou** [comment]
Alright, I think I managed to fix this issue. You won't even need to disable the channels in the Android settings. Now the notification should disappear as soon as you have no unread posts among all active pins (active pin is a thread pin that is not archived/deleted).

But you still won't be able to swipe the notification away!

**Comment by K1rakishou** [comment]
A little update. This thing will work as I said in the previous post except for when you have at least one thread being downloaded. In that case you won't be able to hide the notification when reading all posts and when "Notify about only replies to my posts" setting is turned on. That's because for now there is no easy way to fix that.
