### ISSUE TITLE
[BUG] Thread watcher stops bookmarking threads that match watch filters

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#538]
For some reason the thread watcher sometimes completely stops bookmarking any threads even though there are active threads that match the filters. It's not a case of not waiting long enough for a background update, I had a thread that was created over 24 hours ago not bookmarked even though it matched my filter. The fix I have found is to either force close the app or crash it from developer settings, when you open the app after that all active matching threads immediately get bookmarked and new threads get get bookmarked as they get posted.

I haven't figured out any STR, all that I can say is that the issue seems to appear when the app has been running for a long time, and that the issue has been happening for around a month or a two at least. Possibly maybe around the time the "ignore cleared filter watches" option was added to developer settings.

**Comment by Adamantcheese** [comment]
Yeah I've noticed it as well. It may have been an issue with OkHttp not correctly closing some connections, or with #515. Both of those should be resolved in the next release and hopefully this won't happen anymore.

**Comment by Adamantcheese** [comment]
I'll leave this open until the next release. I keep the application constantly open on my phone, so if anything does fail then I'll know this wasn't resolved. If it doesn't happen again, I'll consider it resolved as of version 4.11.0

**Comment by Adamantcheese** [comment]
Well, it survived the test of Wonder Festival, so I'm going to call this one closed.

**Comment by Adamantcheese** [comment]
Of note: I don't know exactly why, but if you have some sort of battery optimization for applications on your phone, it may be pertinent to change to to not optimize and restart your phone. It seems that battery optimization likes to disable the alarm, which would disable all background updates, including regular thread watching. I've added in a slight adjustment in https://github.com/Adamantcheese/Kuroba/commit/b60e0c98498fb1537d34ebac7990586c64c088b6 so that even if the alarm gets disabled for whatever reason, going out of the app and into it again should trigger the wake manager if it's a good time.
