### ISSUE TITLE
Single tap to pause conflicts with tap to display WEBM playback controls

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#557]
In the most recent Kuroba version when viewing WEBMs a single tap is used to both pause/unpause AND to display/hide the playback controls, so if you want to bring up the controls to view/move the seek bar for example. you end up inadvertently pausing the WEBM at the same time.

Here's a few suggestions to fix it:
1. Have single tap brings up WEBM playback controls, a single tap will pause/unpause only if controls are visible. Playback controls disappear automatically after a few seconds.
OR
2. Have single tap display and hide WEBM playback controls. Double tap is pause/unpause. Since double tap is used to close media with gestures disabled, double tap to pause can only work with gestures enabled.

**Comment by floppyD** [comment]
Making it optional would be great too. I don't think that tapping to pause is necessary since there's already a button for that.

**Comment by Pentaphon** [comment]
1. Tapping the webm to pause it should be completely gone since we have player controls for that. 

1. Player controls should never appear when swiping webms. They should only come up when tapping a webm. 

1. Perhaps a disabled by default but optional webm gesture system could be implemented where when enabled, removes the player controls entirely, and lets users tap the middle of the webm to pause, and tap the left and right of the webm to fast forward or rewind the current webm. Swiping would still always go to the next webm.  Swiping down would close the gallery view.

This is the way.

**Comment by dronewizard** [comment]
Tapping to pause is unnecessary and I won't use it.

**Comment by K1rakishou** [comment]
>Have single tap brings up WEBM playback controls, a single tap will pause/unpause only if controls are visible.

This can actually be easily done by adding a check:
```
PlayerView.isControllerVisible()
```

into the MultiImageViewGestureDetector in some places.

**Comment by dronewizard** [comment]
Tap to pause is better than having player controls.

**Comment by Adamantcheese** [comment]
The following will now be the functionality: Gifs are double tap to pause again, single tap to close. Players now don't display their controls by default, and a single tap will bring them up, and another tap will close the controls and resume playback. Double tapping a video will play/pause it. Also, videos will display if they are buffering.
