### ISSUE TITLE
[BUG] When copying/quoting post text with youtube titles enabled video title is copied instead of the link

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#573]

**Comment by K1rakishou** [comment]
Maybe we could do something I did with the Android 10 gestures exclusions zones editor where you are able to select the zones manually by moving rectangles? I.e. you select a point on the screen where you want this shit to appear, we do some checks so that it won't go out of the view and if it's all ok, then the captcha view will appear at that place.

**Comment by Adamantcheese** [comment]
That's exactly how it's supposed to work for copying. That's how it works on any browser as well, where an \<a\> tag with an href is used. And I can't fix the quoting part because the actual URL is being replaced by the title itself when the post is being parsed; otherwise I can't display a different piece of text on top of the current text.

**Comment by K1rakishou** [comment]
Maybe we could instead of replace it completely introduce some kind of ExtraLinkInfo where we would store the title and duration and the use that for post binding, but for copying the old comment text would be used?

**Comment by Adamantcheese** [comment]
Sounds like a bunch of extra work for something too small to care about.

**Comment by Astridchan** [comment]
Just a suggestion, there's a "show links" option in the post menu, wouldn't it make sense to have a long press on a link in that menu copy the URL into the clipboard, then you could get the YouTube URL even with title parsing enabled.

**Comment by Adamantcheese** [comment]
I can probably do that.
