### ISSUE TITLE
[MEMORY LEAK]s from Leaks Canary

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#581]
![Screenshot_20200207-003254](https://user-images.githubusercontent.com/40862101/73984514-7a31b000-4941-11ea-9a4c-4d0ff610b83e.jpg)

![Screenshot_20200207-002439~2](https://user-images.githubusercontent.com/40862101/73984404-3c348c00-4941-11ea-9e16-a93d01698169.jpg)

![Screenshot_20200207-002505~2](https://user-images.githubusercontent.com/40862101/73984414-40f94000-4941-11ea-8967-920ebe53ee03.jpg)

**Comment by Adamantcheese** [comment]
#1 and #3 aren't really leaking, as the ViewHolder is just inside of the scrap part of the recycler view; only a max of 5 items can be "scrap" by default, and they're reused when possible.
#2 I have no clue. If that one is recent then it's probably with that snackbar change I made recently, which would be weird because I'm nulling it when the view isn't attached to the window.

If there's nothing else I would recommend to close this; I kinda suspect that there's going to get a lot of leaks like this as a result of the single-activity nature of the application.

**Comment by Astridchan** [comment]
These leak reports are kind of gibberish to me so I wasn't sure if it's something that needs to be reported or not. 

>#2 I have no clue. If that one is recent

Happened yesterday. Forgot to mention that this is on the latest Dev build.

>If there's nothing else I would recommend to close this

Ok, I'll do that.

**Comment by K1rakishou** [comment]
#3 looks like a leak in LeakCanary itself, lmao.

>#2 I have no clue. If that one is recent then it's probably with that snackbar change I made recently, which would be weird because I'm nulling it when the view isn't attached to the window.

We probably should cancel all snackbars/toasts when StartActivity gets destroyed. Nulling it won't help since it creates a separate object which is being held somewhere in Snackbar internals. It will get removed in 3seconds or so, but if the activity gets destroyed before it gets automatically removed the leak canary will get triggered. That's technically not even a leak, yes. But still it would probably be a good idea to fix that.

**Comment by K1rakishou** [comment]
Also, do we use the application context for Snackbars too? It may cause the leak as well (and even that one crash we got with toasts).

**Comment by Adamantcheese** [comment]
Snackbars are attached to views, which all of them should somewhere down the line be using StartActivity as their context (not Chan, which is what you get if you call getAppContext()).

**Comment by K1rakishou** [comment]
Oh yes, they require a View not a Context object.
