### ISSUE TITLE
[IMPROVEMENT] enable meme flags [don't delete/lock this, let's talk first)

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#591]
When I saw two of your absurd reasons for not enabling meme flags, I knew you were making shit up. If you hadn't said anything or simply been honest and said "No" or "I hate meme flags, I hate /pol/, soy good, etc", I would've been okay with your decision but instead you came up with two crazy reasons.

Let's start with your first reasoning. https://i.imgur.com/qkjb3VB.png
The first thing you said is completely acceptable. But then you went ahead and said "install 4chanx on your mobile browser". The whole point of an imageboard app like Kuroba is to literally avoid using the mobile browser. Telling people to install 4chanx on a mobile browser and stop using Kuroba is a terrible reason. Your "reason" is a literal oxymoron. 

Your second reasoning. https://i.imgur.com/AAwHdFx.png
You claim Kuroba is meant to work on several *chans, yet there is no support for the biggest imageboards except for 4chan and I don't think Kuroba will ever support the other largest imageboards. I'm not going to say what the other large imageboards are because you know which ones I'm talking about. To be more precise, I'm referring to the original imageboard from Japan, the second largest English imageboard, the various imageboards from France, Germany, Poland and much more. 
Secondly, when somebody downloads Kuroba and adds an imageboard, they expect all of the features on the imageboard to be supported from the app.
I'd say about 90% or more use Kuroba to access 4chan.

**Comment by Adamantcheese** [comment]
1) People _really_ seem to care about this but I don't. Great candidate for someone doing it, like 420chan. Also people keep blabbing about how Kuroba should support all 4chanX features. It won't, and I don't understand that mentality. If you want to use a feature that's in 4chanX and not in Kuroba, either use 4chanX or submit a PR.

2) Yes, it does in fact support several *chans; because *chans are different via configuration, there's not always a good one-implementation-fits-all method for supporting them, so your imageboard of choice may not be implemented. Those ones weren't added previously in Clover and by and large they're added by request or by someone working on them (like 420chan). And yeah, it's pretty obvious it's focused on 4chan, duh. If you want to use those imageboards in an app, there are plenty of alternatives that do support them, and porting over their implementations as a PR would be the route to go if you want them in Kuroba.

Also changing your flag isn't a feature to the imageboard by default, and is only exposed via 4chanX.
Understand that while I support this application and make the choices I feel are best for it, I am not obligated to add your features. It's open source if you want to do it yourself.

**Comment by K1rakishou** [comment]
I'd just like to interject for a moment.

>yet there is no support for the biggest imageboards except for 4chan and I don't think Kuroba will ever support the other largest imageboards.

We, as developers, only provide you, the community, the means (tools) to implement that functionality. Everything else after that depends on the community. That is because there are lots of different chans and, obviously, developers don't use and don't care about all of them (I, personally, only care about 4chan because I'm using it the most).

I only did add 8kun because: 
1. People are spamming about it in every single thread. 
2. We kinda promised to add it in this update (even though we didn't manage to do it in the end because there were already too many things) 
3. And there already was a working 8kun PR on Clover repo. I just moved it here and tested a little bit.

**Comment by ghost** [comment]
@Adamantcheese It's obvious that you don't care about this. You could've said "no" or nothing at all and I wouldn't care, but your reasoning is what's hilarious. 

I am not sure why you are bringing up 4chanx. I have never requested 4chanx features into Kuroba. Most of the features on Kuroba, if not all, are the exact same features that people can find on 4chanx, such as randomizing the filename's timestamp and so on.

Also, being able to change your flag on some imageboards has nothing to do with 4chanx or any other userscript. That feature is provided by the imageboard itself. Like I said before, when somebody adds their imageboard to Kuroba, they expect all of the basic features to be supported. https://i.imgur.com/KckFOyR.png

**Comment by Adamantcheese** [comment]
I was under the assumption that it was a 4chanX feature, shows how much I go on those boards. When I went snooping in their code, some extra POST was being sent with a flag code, which is why I thought that it was some non-native feature that 4chanX was fiddling with. I'll add in some basic amount of support, but if anyone wants something more or for a different board, I'll only accept a PR.

It may be the case that whatever 4chanX is doing with the extra POST call is because boards other than /pol/ don't have that field in their reply forms. I was only really checking /int/ for flag stuff anyways.
