### ISSUE TITLE
[BUG] WebM's with sound start playing in the background even when they're supposed to be muted, only way to stop it is FC'ing app

### ISSUE THREAD

**Issue by Astridchan** [Adamantcheese/Kuroba#62]
Steps to reproduce:
1. Find a thread that has WebM's with sound (in /wsg/ for example)
2. Open a WebM and start swiping through them quickly (don't wait for them to load)
3. Audio for the WebM's you have swiped past will start to play in the background (even when WebM's are set to be muted by default)
4. Only way to stop the background audio from playing is to force close the app from settings

**Comment by Adamantcheese** [comment]
@ekisu if you want to take a look at this, you know more about your own code than me. I just made it work the best I could.

**Comment by ekisu** [comment]
I think this happens because it calls `MultiImageView.openVideoInternalStream` for many MultiImageViews, and when the MediaSource is loaded (which may happen after the user has switched images) it creates an ExoPlayer, adds the `AudioListener` to it, and the `onAudioLoaded` callback goes to `ImageViewerPresenter`, which only mutes the video if it's the current post image.

I'm not sure how to fix it though.
