### ISSUE TITLE
[Feature Request] Extraflags Support

### ISSUE THREAD

**Issue by maluhia** [Adamantcheese/Kuroba#67]
There is a popular userscript that I and many anons contribute to and use, that allows one to set optional provincial/state flags when they post: https://github.com/flaghunters/Extra-Flags-for-4chan
![image](https://user-images.githubusercontent.com/33070562/59165928-19af5200-8ad8-11e9-8a89-fed870605a78.png)

Please add support for this! It would be greatly appreciated.

**Comment by Adamantcheese** [comment]
So as far as I can tell, this is using an external website to the *chan to store the extra flag data?

**Comment by maluhia** [comment]
Yes, people install a userscript. They set their desired state and city flags, and when they post, it sends their selected regional flags to the db along with the post number. Nothing else is saved, and there is no logging. I can provide proof of this in a PM. Old regionals are deleted from the db when the thread 404s (either deleted by mod, or deleted from 4chan archive)

Upon loading a thread, the userscript checks the post number against the db and pulls all selected regionals.

Currently, it only supports 4chan/4channel.

Feel free to ask anything, or head over to the >>>/int/extraflags general and see it in action.

**Comment by Adamantcheese** [comment]
For essentially the same reason as #138, I'm closing this. The app is meant to be focused on *chans themselves, not extensions to them. While I understand that this would be a great addition, especially if you're doing a roadtrip or something and want to collect regional flags, this app is not meant for that. Additionally, becase it only supports 4chan and only a few boards at most (int, bant, and pol afaik are the only ones that support flags), it's not really a candidate for board specific functionality; the code tags feature on /g/ was already something I didn't feel was right adding because it was a board specific feature, but was low impact enough (codewise) that it was added. As a workaround, just like in the issue mentioned, using a mobile browser with the userscript installed is satisfactory for the use cases I can think of.

If you or someone else feels like adding this feature in, please submit a PR.
