### ISSUE TITLE
[Implement] Add post cool down. 

### ISSUE THREAD

**Issue by Yoirkie** [Adamantcheese/Kuroba#746]
Would be nice to implement a post cool down.
" You must wait longer before posting a new thread"

**Comment by Adamantcheese** [comment]
Uhh, it's already in there? Unless you mean something else? See LastReplyRepository.

**Comment by Pentaphon** [comment]
@Adamantcheese I think he means a visible counter like 4chan X has so you can see it count down from 500 to 0 so you know when a new thread can be made if you want to make 2 threads at the same time on the same board. 

Same with posting, but I think cooldown timers when posting replies are even more important and doable than new threads.  A visible countdown from 60 to 0 instead of hitting the button and seeing "you must wait X seconds before making a new post" would be very useful when replying in a fast-paced thread.

**Comment by Adamantcheese** [comment]
Ah, duplicate of #15 then.
