### ISSUE TITLE
Replace hardcoded sites

### ISSUE THREAD

**Issue by namazso** [Adamantcheese/Kuroba#78]
Instead of the current hardcoded one interface for each site method I think choosing based on some sort of compatibility test would considerably increase amount of sites the app is compatible with.

**Comment by Adamantcheese** [comment]
Because a number of sites require an amount of configuration, there isn't really an easy way to do this. Other *chan applications use a plugin system for each site they support, which is basically the same thing that's being done here, for basically the same exact reason of every site is more unique than you'd think.
