### ISSUE TITLE
Add option to disable local post timer

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#8]
Would be nice to be able to disable it for situations where the timer is changed or unwanted

Examples:
- 4chan pass users, cooldown is only 30 seconds
- Changed IP, cooldown doesn't apply
- Trying to pre-fill a captcha to post at a precise time for dubs or whatever

**Comment by Adamantcheese** [comment]
1) Some boards have reply timers of 15 seconds or 90 seconds. Currently the local timer is for 60 seconds, which is wrong and will be fixed. However, I don't know what the 4chan pass does to the timer, if it's exactly half the time, a max of 30 seconds, or anything. Please tell me what happens in that case. You can check what the timers are by looking at http://a.4cdn.org/boards.json (/b/ is one with 15 seconds, /vg/ is 90)
2) This isn't a problem I'm going to solve because it would be too much of a hassle to code. Deal with waiting an extra couple of seconds if that happens, or do it yourself and submit a PR.
3) Loldubs

**Comment by ghost** [comment]
Done some testing - it halves it everywhere.
