### ISSUE TITLE
[MEMORY LEAK/BUG] Bitmaps are never recycled in ThumbnailView

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#834]
This is especially noticeable with prefetching/hi-res cells turned on in catalog/album.
Turns out we just never recycle old bitmaps when replacing it with another/nulling it out which leads to memory leaks.

![234234234](https://user-images.githubusercontent.com/10332458/77250348-7db29980-6c58-11ea-997e-50233df83cdc.png)

https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/view/ThumbnailView.java#L344

Simply recycling them won't work because we apparently do not reload them on post bind. So it's not gonna be easy.

**Comment by K1rakishou** [comment]
Alright, it's actually turned out to be way easier than I had expected. Will be fixed in https://github.com/Adamantcheese/Kuroba/pull/810

**Comment by Adamantcheese** [comment]
There is no issue here, the LRU cache is working as intended. If you had scrolled, the LRU cache would have purged entries and because the Bitmaps were no longer referenced anywhere, they would be garbage collected. Note that the AVD you're using has 1536MB by default, and the BitmapLRUCache instance holds 192MB max of bitmaps (1/8 the RAM total).
