### ISSUE TITLE
Question regarding Captcha

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#854]
Why are they so bad on Kuroba? I know cookies were supposed to solve this issue but I have been trying them for months since the feature was introduced and they didn't change anything, I tried with cookies from mobile Chrome, Firefox and Chrome from PC and nothing, despite getting good results on their respective browsers.

Someone in a thread suggested that I might be typing them wrong or something, but the issue isn't that either, I got to the point of typing them manually and triple checking everything for errors.

So any idea? Here's a video showing that even the captcha under the WebView report page works just fine, while the one built in Kuroba is really bad. Yes, it's reproducible, every single time I try I get similar results, if not better on WebView, since it sometimes don't even ask for a solution.
https://files.catbox.moe/whtbs7.mp4

**Comment by Adamantcheese** [comment]
Captcha is basically entirely out of my control. A better question would be to ask Google how they work but that would entirely defeat captcha's purpose. Likely Google is doing some sort of IP tracing for spam, User-Agent tracking as well, as well as applying extra checking for certain sites I would assume. Currently the User-Agent field is set to "Kuroba/v4.12.0" or whatever the current release is; Clover used a similar User-Agent field.

If a similar issue happens with Clover, it's likely because something isn't being loaded properly due to the captcha html not being similar to 4chan's native stuff. I wouldn't be surprised if the captcha JS library does a bunch of snooping about what's loaded in the browser to make sure people aren't doing shady shit. But I don't know what I could really do about that.

**Comment by floppyD** [comment]
But is it that bad for everyone or just me? And what happens if you change the User-Agent to Chrome? By the way, I just downloaded Clover again and it's equally bad. Fuck JS Captcha to be honest.

**Comment by Adamantcheese** [comment]
It seems to only affect specific people; I don't have any issues using cookies from my browser and avoid basically every captcha, wifi or mobile data.
The NoJS Captcha used this User-Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36`; it looks like other *chan apps are using that sort of User-Agent string. I could give it a try. No guarantees however because if it's the same on Clover, there's still a chance it's the site-snooping javascript. That's a whole pile of obfuscated Javascript that a security researcher would probably have more luck determining how to break.
For now I'll try out the User-Agent string change.

**Comment by floppyD** [comment]
Just quad checking now, is that really the cookie structure? Anyway, I'll report if the user agent change does anything.

![Screenshot_20200423-022212_Kuroba](https://user-images.githubusercontent.com/29208110/80062361-eb790c00-8509-11ea-96b4-0910e75569df.png)

**Comment by Adamantcheese** [comment]
Yup, all of that looks correct to me. I may take a little bit to get around to making that change as the thing I'm currently working on (themes cleanup) I can't really stash my changes to go quick put that in. If you want to have it right now, you can go change USER_AGENT in the NetModule class to be the one in CaptchaNoJsPresenterV2 and submit a PR for that, which I'll merge in so you can go test that. Don't even need Android Studio, just git and a text editor.

**Comment by floppyD** [comment]
Just change
`USER_AGENT = getApplicationLabel() + "/" + BuildConfig.VERSION_NAME;`
to
`USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36";`
right?

**Comment by Adamantcheese** [comment]
Yup!

**Comment by floppyD** [comment]
Nothing changed, if it isn't the fading shit it's that one that keeps asking you to solve more and more, and as always, first try on browser/WebView. My phone must be cursed or something.

**Comment by Adamantcheese** [comment]
Captcha works in mysterious ways. Every other way that Captcha might be doing stuff is basically beyond my control or ability to help. Sucks, but that's how it is. I'll leave this open for a bit longer if any ideas come around.
