### ISSUE TITLE
The post reply window is garbage, improvements are a must now.

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#867]
It's annoying to have to add "sage" or a new code to flags to my post whenever I want to post with it.
It needs to stay there permanently until I decide to remove it.

**Comment by lewri** [comment]
Looks like the options field does reset after every post in a thread.

I say 'thread' because it looks like the 'name' field is unique to each thread. However, something of further investigation may also be preserving the 'name' across sessions. I noticed if you exit Koruba and come back, the name field goes blank. I would imagine mobile users may exit and re-enter the app multiple times across the lifetime of a thread, so may be ideal to keep that info.

Back to the original question though, I'm not sure why you'd want to be permanently in 'sage' mode. Nevertheless, maybe an option to preserve the 'options' field on a thread-by-thread basis could be beneficial.

**Comment by Adamantcheese** [comment]
Flags can be set per-site. Saging every post is dumb. Default names can be set in the global settings of the application.
