### ISSUE TITLE
(dev) what happened to tapping post numbers?

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#882]
I just updated and I noticed and I can't reply with it anymore. Is it gone for good?

**Comment by Adamantcheese** [comment]
Double tap now, no setting.

**Comment by ghost** [comment]
I should have tried that. Still, I think the visual effect that highlights the upper post segment on tap is a bit unpleasant considering long press does nothing
I don't want to ask for something that will just clutter the options menu, but with this and a couple other unintuitive actions I think it would be best to have a separate menu that allows for customizing when they happen

**Comment by ghost** [comment]
Also, I noticed that this makes it impossible to tap post numbers when viewing a post in the reply menu since double tap will send you to the post. I can't stress enough how nice it would be to be able to customize these sorts of actions

**Comment by Adamantcheese** [comment]
Per your comment, it has changed to long click. I disabled the details tap in popups because I thought of that as a bug; it's back. And no, I won't give customization options. You want customization options, submit a PR for it, otherwise I'm going to spend the rest of existence dealing with people wanting it their way.

**Comment by ghost** [comment]
Thanks for explaining
