### ISSUE TITLE
Enabling sound for images

### ISSUE THREAD

**Issue by MegaPramuk** [Adamantcheese/Kuroba#888]
Hello there.
There's an extension for 4chanX that enables sound for images that lead to sound threads being more common.
It would be great if kuroba could support those.
[Here's](https://greasyfork.org/en/scripts/31045-4chan-external-sounds/code) the code of said extension.

**Comment by ghost** [comment]
No offense but isn't this feature bloat? It's kind of niche.

**Comment by Adamantcheese** [comment]
This would be possible, however only if the image in question was a WEBM with an https link to the source audio. And it kinda is feature bloat, considering hotlinking is a thing and you can just shove a link into your post to another post on a board that does support WEBM audio. I know that this is being requested because some script is being used more frequently now, but there already is a workaround. Plus I can already see the requests for "download and encode these into WEBMs for me" which is a massive undertaking to shove FFMpeg into an application for one specific case.

**Comment by Adamantcheese** [comment]
I've  decided to not include this feature. While it it neat, because of deficiencies in implementation that  cannot easily be worked around I'm choosing not to do this. It's still up for anyone to implement themselves and submit a PR though.
