### ISSUE TITLE
Android 10 dark theme api support

### ISSUE THREAD

**Issue by articpinecone** [Adamantcheese/Kuroba#898]
Kuroba should support the dark theme [api ](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme)that android 10 provides. The user can set two of the included themes in the app as the light theme and dark theme. 

For example if a user chose yotsuba as their light theme and Black as their dark theme whenever the android device has dark mode turned off the kuroba app would use yotsuba and whenever the android device has dark mode turned on the kuroba app would use Black.

I'm sure there's people who use kuroba both during the day and late at night who would appreciate this feature.

**Comment by articpinecone** [comment]
To simplify things even further instead of having a light theme and a dark theme there could just be the normal default theme the user sets (like it is in the current version of the app), and if the app is installed on an android 10 device a sub-menu option could pop up in the appearance section asking the user if they want to set an alternative kuroba theme for when their device is in dark mode.

**Comment by Adamantcheese** [comment]
So here's my notes: you can pick two themes now on Android 10 and above with the sun/moon toggle in the theme settings controller, one at a time and the application will restart after each selection. However, when the theme switch happens, the application will restart because I couldn't find a way of having the correct theming without duplication of stuff in styles.xml and I couldn't re-inflate all the layouts to have the right colors. So it might be a bit clunky, but I think it's a "good enough" for a first prototype.
On Android 9 and below, it'll work exactly the same as before, no impact at all.

**Comment by articpinecone** [comment]
sounds perfect, this is my first time contributing to open source repos btw so apologies for any conventions I may have broken. If I have time I could help with implementing this feature too.
