### ISSUE TITLE
Report "the app is extremely slow on android 10 at catalog mode"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#976]
UUID: 7bb6bf199128ecff9a7f0e4dbcef12c9
Build flavor: stable
Version name: v4.13.4
OS info: Android 10, sdk version: 29
Report description: constant stuttering, jittery scrolling and crashes or freezes when moving to next picture while watching a video or gif

**Comment by ghost** [comment]
Doesn't happen to me
Generally the app is pretty smooth
Edit: except images not loading, I'll make a post about that

**Comment by Adamantcheese** [comment]
I don't have any performance issues on my Android 10 phone, but 4.13 did remove Volley so some performance impact may have occurred there.
@clawyf Images not loading has been taken care of on dev with #966 and #977; there still may be a few images that error out if you scroll fast enough due to an HTTP/2 stream reset exception which I can't pinpoint the reason for. Setting the experimental setting for disabling HTTP/2 would prevent any issues of that sort, as Volley was probably only using HTTP/1 for image loading.

I'll leave this open if anyone can provide additional resources for this issue.

**Comment by floppyD** [comment]
It's probably this, some images really fuck things up here. Android 9 and 4.13.4
https://streamable.com/bvf7xc

**Comment by K1rakishou** [comment]
@floppyD It looks like you are using hi-res cells, right? Then this is probably because of the GC kicking in every second because we don't recycle bitmaps manually upon image unbinding. I had similar freezes when using hi-res cells in gallery. I remember fixing it by manually recycling every bitmap upon unbind() but I don't remember that fix getting merged.

**Comment by Adamantcheese** [comment]
#834 is the issue you're talking about here. Hi-res cells were changed in a recent dev change and should be a lot less memory intensive in terms of what the LRU cache stores.
