### ISSUE TITLE
Board search is a bit quirky

### ISSUE THREAD

**Issue by ghost** [Adamantcheese/Kuroba#979]
The current board search system has an odd priority between the letter codes and the actual titles. In my opinion, it would be best to give priority to the letter code if that's what has been typed in. If "a" is typed in, you get /aco/ /adv/ /an/ /asp/, and then /a/. Typing "an" moves /a/ to nearly the bottom of the list, and even "ani" puts /an/ /his/ and /w/ before /a/

Side note: why does typing "anime" show /w/ then /a/ then /c/? I can't see any pattern here.

**Comment by Adamantcheese** [comment]
So there's currently two different search methods, used in different places, back from when Floens implemented it. I changed the second one, which is used in the site board selection window, to move an exact board code match to the top of the list, otherwise everything is sorted using a fuzzy comparison.

However for the floating boards menu, which I presume is the one you're talking about, it looks like it returns a list of boards where it puts board codes that start with your query first, followed by board names that contains your query, followed by everything else. That explains the "a" result and why "an" and "ani" move things to the top, because /an/ is an exact code match, followed by /his/ which is "History & Hum**ani**ties", and /w/ which is "**Ani**me/Wallpapers" and /c/ is "**Ani**me/Cute". It doesn't do any special sorting for lexicographic ordering which is why they're in a somewhat random order.

If it would be preferred, when filtering in the boards floating menu, I could just have it use the same sorting as the site board selection menu, which would probably make it a bit more understandable?
